### ISSUE TITLE
톡톡 이미지 post 문제

### ISSUE THREAD

**Issue by gentlepie** [navertalk/chatbot-api#1]
이미지 처리에 문제가 있습니다.
서버에서 이미지를 최초로 보냈을 때 사이즈가 width : 0 height : 0 으로 계산되어 표시되지 않다가
>![2017-07-26 11 15 08](https://user-images.githubusercontent.com/25915751/28601791-4c8ebb64-71f5-11e7-9d86-7b1b8d139a8d.png)

새로고침을 누르면 NaNpx로 설정되면서 화면에 표시됩니다. 
>![2017-07-26 11 15 37](https://user-images.githubusercontent.com/25915751/28601785-4782d24a-71f5-11e7-89fd-8f2c0075f1ee.png)

이미지 전송은 post로 톡톡 보내기 API를 이용하였습니다.

**Comment by navertalk** [comment]
@gentlepie 
안녕하세요. 네이버톡톡 입니다.
말씀해주신 문제 확인 후 수정하여 배포하였습니다.

이렇게 관심가져 주셔서 감사드립니다.

'첫번째 이슈'를 달아주신 '1빠' 기념으로 마음을 담아 소정의 네이버 로고샵 선물을 드리고자 합니다. ^^
시간되시면 naver_talk@naver.com 으로 배송 받으실 주소지 전달 부탁드립니다.

감사합니다.

**Comment by gentlepie** [comment]
감사합니다 ㅎㅎ
