### ISSUE TITLE
List 상에서 네이버톡톡 로딩 시, 다수의 script 와 css 생기는 현상

### ISSUE THREAD

**Issue by MG-K** [navertalk/chatbot-api#10]
지금 현재, 쇼핑몰에서 list 형태의 페이지를 보여줄 경우
각 상품옆에 네이버 톡톡을 추가한 상태인데, 로고추가 후, 제공해주는
소스로 붙여넣기해서 사용하고 있습니다.

<script type="text/javascript" src="https://partner.talk.naver.com/banners/script"></script>
<div class="talk_banner_div" data-id=""></div>

문제는 상품이 50개가 보이면
50개의 script 와 css 파일들이 추가되는 것을 확인했습니다.

해당 버튼 갯수만큼 별도로 선언을 해야하는걸까요?
소스를 봐도 동일해서 굳이 동일한 script 와 css 가 여러개 선언될 필요는 없는거 같아 보입니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

네이버톡톡 파트너센터의 [톡톡배너만들기] 에서 생성하신 배너스크립트코드를
쇼핑몰 페이지에 추가하는 부분을 말씀하시는 것 같네요.
(chatbot-api 와는 관련은 없습니다.)

말씀주신대로,
<script type="text/javascript" src="https://partner.talk.naver.com/banners/script"></script>
부분은 페이지에서 1번만 로딩되면 됩니다.

<div class="talk_banner_div"...></div> 부분만 실제 노출될 상품영역에 각각 추가해 주시면 됩니다.

감사합니다.

**Comment by navertalk** [comment]
@MG-K 
안녕하세요.
네이버톡톡입니다.

위 답변에 좀더 설명드리면 상품마다 `div`를 사용하시고 하단에 `script` 하나만 삽입하시면 됩니다.

```html
<ul>
  <li>
    A상품
    <div class="talk_banner_div" data-id="99999" data-ref="https://shopping.com/product/a"></div>
  </li>
  <li>
    B상품
    <div class="talk_banner_div" data-id="99999" data-ref="https://shopping.com/product/b"></div>
  </li>
</ul>

<script type="text/javascript" src="https://partner.talk.naver.com/banners/script"></script>
```

또한 `data-ref`를 사용하여 각 `배너`마다 채팅창 유입시 별도의 상품정보 말풍선을 노출할 수 있습니다.
`data-ref`에 사용될 URL은 반드시 `URL인코딩`이 되어있어야 합니다.
상품정보에 대한 좀더 상세한 설정은 http://blog.naver.com/naver_talk/220876525806 를 참조해주세요.

감사합니다.

**Comment by MG-K** [comment]
이쪽에서 담당하시는게 아니란것은 알지만 ㅠ 문의를 해도 개발적인 이슈를 처리못해준다고 이곳에 문의하라고 하더군요. 답답한 마음에 적었는데 답주셔서 감사합니다 ^^

마지막으로 하나 더 문의를 드릴것이 있습니다.
네이버 톡톡으로 해당상품의 정보(상품명, 이미지) 등을 보여주려고 하는데 meta 태그를 이용하면 된다고 되어있는데 해당 부분외에 별도로 설정해야할 부분들이 있을까요?
