### ISSUE TITLE
상담완료 기능에 대한 개발 문의 드립니다.

### ISSUE THREAD

**Issue by bungmat** [navertalk/chatbot-api#100]
안녕하세요 : )
네이버톡톡 API를 이용하여 채팅서비스를 운영하고있습니다

API를 이용해서 네이버톡톡에서 상담완료처리를 하고 문의 건수에서 제외 될 수 있도록 구현하고자 합니다.

제공된 API 메뉴얼에 상담 완료에 대한 기능이 없던데 제공이 가능할까요?

제공이 불가능하실경우 개발 일정이 있으실까요?

확인 부탁 드립니다.

감사합니다.

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다.
먼저 서비스에 좋은 기능을 제안해주셔서 감사합니다!
현재는 상담 상태를 제어할 수 있는 API 제공이 되지 않고 있지만,
차후 API 버전에 해당 기능의 추가여부를 검토해보도록 하겠습니다.
API 업데이트 소식은 Github을 통해 전달드리겠습니다~
오늘도 좋을하루 되세요. 감사합니다.
