### ISSUE TITLE
send 이벤트 inputType Inquiry 질문

### ISSUE THREAD

**Issue by billopark** [navertalk/chatbot-api#103]
[문서](https://github.com/navertalk/chatbot-api#textcontent) 에 따르면 inquiry는 오른쪽 위의 상담 요청 레이어에서 상담 요청하기 버튼을 누른 경우 라고 안내되어 있는데요,

제 톡톡 응대화면 UI에서는 상담 요청하기 버튼이 보이지 않아서 상담 요청하기 버튼이 존재하는 페이지의 예시가 궁금합니다.

그리고 inquiry 타입의 send event의 example payload도 어떻게 되는지 궁금합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

죄송합니다. `상담요청` 기능은 톡톡상담센터에서 없어진 기능입니다. 😥
관련해서 문서를 최신화하도록 하겠습니다.

감사합니다.
