### ISSUE TITLE
webhook 응답을 받지 못하고 있습니다.

### ISSUE THREAD

**Issue by pincoin** [navertalk/chatbot-api#105]
안녕하세요.

여기 깃헙 이슈에 등록된 내용 curl 명령어로 테스트가 정상적으로 동작합니다.

```
curl -H "Content-Type: application/json" -XPOST -d'{"event":"send","user":"7_iLCNlYzvB5K43l2Kvlog","textContent":{"text":"hi","inputType":"typing"},"options":{"mobile":false}}' "등록웹훅주소" -v
```

톡톡 아이디값은 `WC0CN9`이며 혹시 웹훅 URL의 끝에 `/`가 붙으면 안 된다거나 cloudflare 뒤에 있으면 안 되는지 확인 부탁드립니다.

감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

구성하신 서버에선 헤더에 `user-agent`가 없을 때 훅이 전달되지 않는 것을 확인하였습니다.
검토 결과 저희가 전달하는 훅에 `user-agent`를 넣는 것이 적절하다고 판단하였고,
`navertalk/v1`으로 넣어서 전달하도록 배포완료하였습니다.
위에 적어주신 계정으로 훅이 전달되고 응답이 오는 것까지 확인하였습니다만,

`{"event":"send"}`

이렇게만 보내고 계셔서 유저에게 메시지가 뜨지 않고 있는 상황임을 참고하시기 바랍니다.
이슈 문의 감사드리며, 앞으로 많은 이용 부탁드리겠습니다.

**Comment by pincoin** [comment]
네. 이벤트 수신 확인했습니다.

수신이 안 되서 더 이상 진행하지 못해 일단 `{"event":"send"}`으로만 응답처리했었습니다.

빠른 조치에 감사드립니다.
