### ISSUE TITLE
Profile API로 프로필 요청시 API 및 webhook사용이 중지될 때 처리

### ISSUE THREAD

**Issue by ayaaason** [navertalk/chatbot-api#112]
Profile API로 프로필 요청시 엔드유저가 승인을 바로 안하는 경우 API 및 webhook사용이 중지되는 걸로 알고 있는데 이때 처리는 어떻게 하는게 좋은지 알려주실 수 있으신가요??

특히 엔드유저 챗팅 화면에서 봤을 때는 중지됐을 때도 메시지를 연속으로 보내면 제대로 보내지는 것 같이 보여서 혼란을 일으킬 거 같아서 적절한 처리 방법이 있으면 알려주시면 감사하겠습니다!!

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다.

> ![image](https://user-images.githubusercontent.com/30263758/64602719-425a2700-d3fa-11e9-9e84-0e33ec51dc94.png)
> https://github.com/navertalk/chatbot-api/blob/master/profile_api_v1.md#profile-api-%EB%8F%99%EC%9E%91-%ED%9D%90%EB%A6%84

Profile API 활용 시 엔드유저가 승인하지 않은 경우  `"result":"CANCEL"`와 같은 이벤트 응답을 전달하고 있습니다. 해당 응답을 활용하여 이후의 처리를 구현할 수 있습니다 🙏 .

**Comment by ayaaason** [comment]
답변 감사드립니다! 

승인하기 않기를 누른 경우 "result":"CANCEL" 가 올 거 같은데요. 승인을 기다리고 있는 1분동안에는 아무 이벤트가 오지 않고 API 및 Webhook 사용이 중지되는 걸로 맞나요?
