### ISSUE TITLE
파트너 id 검증

### ISSUE THREAD

**Issue by billopark** [navertalk/chatbot-api#115]
안녕하세요.
파트너 ID에 대해서 질문드립니다.
현재 저희 서비스에서 파트너ID 대신 네이버아이디를 입력하는 경우가 왕왕있어서  validation을 넣으려고 하는데요, 

1. 파트너 ID는 대소문자 구분이 있는지 궁금합니다.
2. 파트너 ID의 패턴을 ```wc[a-z0-9]{4}``` 로 간주해도 괜찮을지 궁금합니다.

감사합니다.

**Comment by navertalk** [comment]
안녕하세요 네이버톡톡입니다😄

1. 파트너 ID는 대소문자 구분하지 않습니다.
2. ` wc[a-z0-9]{4}` 패턴으로 간주해도 "괜찮"습니다. 다만, 항상 파트너ID가 해당 패턴을 따른다고 보장할 수는 없습니다. 또한 wc로 시작하는 네이버아이디를 입력할 가능성도 있기 때문에, 패턴 validation 실패시 사용자에게 주의를 주는 수준에서 활용하실 수 있겠습니다.

즐거운 하루 되세요!
