### ISSUE TITLE
from 파라미터 상세 내용에 대해 문의드립니다.

### ISSUE THREAD

**Issue by syoh0708** [navertalk/chatbot-api#117]
https://github.com/navertalk/chatbot-api
에 나와있는 설명이 조금 명확하지 않은 것 같아 문의드립니다.

제가 이해하기로 네이버톡톡 링크에 query parameter로 from 값을 넘기면
https://talk.naver.com/wc1234?from=1234

open event 수신 시에 아래와 같이 전달받을 수 있는 것으로 이해했습니다.
"options": {
     "from": "1234"
}

1. from parameter의 위 사용 방법이 맞는지
2. from parameter의 제한 사항(byte 수, 허용 문자 (regex))이 있는지

답변주시면 감사하겠습니다.

**Comment by ddaying** [comment]
@syoh0708 
아래와 같은 형태로 수신됩니다.

{"event":"open","user":"유저고유정보","options":{"inflow":"button","referer":"https://www.mywebsite.com?naverTalkId=1234&from=1234","friend":false,"under14":false,"under19":false,"unreadMessage":false,"noReflectBot":false,"mobile":false}}

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다. 
@ddaying 님, 안내 감사합니다 👍  
언급해주신 것 처럼 open 이벤트의 `options.from` 값으로 전달됩니다.

> from parameter의 제한 사항(byte 수, 허용 문자 (regex))이 있는지

현재 명시적인 제한사항은 없습니다. 단, URL 인코딩 된 from 파라메터는 챗봇에 전달시 URL 디코딩 된후 UTF-8  문자열로 전달됩니다.

감사합니다.

**Comment by syoh0708** [comment]
@ddaying @navertalk 답변 감사드립니다 :)
