### ISSUE TITLE
네이버 페이 결제 취소

### ISSUE THREAD

**Issue by gentlepie** [navertalk/chatbot-api#12]
네이버 페이 진행하다가 사용자가 취소 버튼을 눌러서 다시 채팅창에 유입시 pay와 관련된 event가 넘어오지 않습니다. 사용자가 취소를 누를경우 event가 발생하게 할 수는 없나요?

**Comment by navertalk** [comment]
안녕하세요. 네이버 톡톡입니다.

이 부분은 이벤트를 발생시킬 지를 고민을 했던 부분인데요. 
현재 이벤트를 발생하지 않도록 한 이유는, 취소 버튼을 눌렀을 때는 결제가 실패한 상황(잔고 부족, 카드 사용 불가 등)은 아니고 UI back과 같은 페이지 네비게이션 액션에 해당하는 것으로 간주하여 결제 이벤트를 주지 않은 것이었습니다. 사용자는 여전히 해당 버튼을 눌러 결제를 성공할 수 있으므로, 챗봇에게 별도의 이벤트를 전달할 필요가 없는 것으로 보였습니다. 

그러나 해당 상황에 대한 별도 처리가 필요한 상황이므로 `pay_complete` 이벤트를 발생시키도록 처리하겠습니다. 수정 배포 후 공유드리겠습니다.

감사합니다!
