### ISSUE TITLE
채팅글 읽음처리 options.readBySend 작동 문의

### ISSUE THREAD

**Issue by kwon2s** [navertalk/chatbot-api#123]
안녕하세요.
네이버톡톡입니다.

https://github.com/navertalk/chatbot-api#send-이벤트-구조 를 보시면, `options`에 `notification` 여부를 넣을 수 있는데요. `readBySend` 라는 옵션을 추가로 넣으실 수 있습니다.

```json
"options": {
  "readBySend":false, /* 읽음처리할 때 사용 */
  "notification": true /* push를 보낼 때 사용 */
}
```

이 옵션은 챗봇이 메세지를 보내는 시점에 `읽음처리`한다는 의미이며, `읽음처리` 후 숫자 뱃지는 초기화됩니다. 여태까지 공개적으로 오픈하지 않았던 속성인데 이번 기회를 통해서 오픈하게 되었네요.

재밌고 인기있는 챗봇 기대하겠습니다. 감사합니다.

_Originally posted by @navertalk in https://github.com/navertalk/chatbot-api/issues/109#issuecomment-518051690_

--------------------------------------------------------------
해당 답변을 보고 다시 질문 드립니다.
안녕하세요 일정상 읽음처리를 이제 하게 되었습니다.
해당 기능 적용을 해보니 읽음처리로 안되어져 다시 문의를 남깁니다.

전송하는 데이터는 아래 출력을 했습니다.

0|miraecht | 2020-02-04 10:25 +09:00: { event: 'send',
0|miraecht | 2020-02-04 10:25 +09:00: user: 'xqLPIz2SsRDL1Uhc2AoiVw',
0|miraecht | 2020-02-04 10:25 +09:00: textContent: { text: '답변 합니다. 읽음처리 초기화 해주세요' },
0|miraecht | 2020-02-04 10:25 +09:00: options: { readBySend: true, notification: true } }
0|miraecht | 2020-02-04 10:25 +09:00: { success: true, resultCode: '00' }

0|miraecht | 2020-02-04 10:28 +09:00: { event: 'send',
0|miraecht | 2020-02-04 10:28 +09:00: user: 'xqLPIz2SsRDL1Uhc2AoiVw',
0|miraecht | 2020-02-04 10:28 +09:00: textContent: { text: '이것도 답변 합니다.' },
0|miraecht | 2020-02-04 10:28 +09:00: options: { readBySend: false, notification: false } }
0|miraecht | 2020-02-04 10:28 +09:00: { success: true, resultCode: '00' }

0|miraecht | 2020-02-04 10:28 +09:00: { event: 'send',
0|miraecht | 2020-02-04 10:28 +09:00: user: 'xqLPIz2SsRDL1Uhc2AoiVw',
0|miraecht | 2020-02-04 10:28 +09:00: textContent: { text: '답변 합니다 2' },
0|miraecht | 2020-02-04 10:28 +09:00: options: { readBySend: true, notification: false } }
0|miraecht | 2020-02-04 10:28 +09:00: { success: true, resultCode: '00' }

0|miraecht | 2020-02-04 10:28 +09:00: { event: 'send',
0|miraecht | 2020-02-04 10:28 +09:00: user: 'xqLPIz2SsRDL1Uhc2AoiVw',
0|miraecht | 2020-02-04 10:28 +09:00: textContent: { text: '답변 합니다.' },
0|miraecht | 2020-02-04 10:28 +09:00: options: { readBySend: false, notification: true } }
0|miraecht | 2020-02-04 10:28 +09:00: { success: true, resultCode: '00' }

옵션값이 서로 틀려서 그런줄알고
readBySend: true, notification: true
readBySend: false, notification: true
readBySend: true, notification: false
readBySend: false, notification: false
를 해도 여전히 읽음 처리가 안되었습니다.

결과리턴은 정상적으로 성공으로 출력이 되고 있습니다.
해당 부분 제가 어디를 실수 했는지 답변 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

확인해보니 해당 옵션과 관련된 비즈니스 로직에 버그가 있었습니다. 현재 운영환경에 배포되어 정상적으로 동작하는 것을 확인하였습니다.

감사합니다.

**Comment by kwon2s** [comment]
답변 확인 및 기능 정상작동 확인 하였습니다.
감사합니다.
