### ISSUE TITLE
persistentMenu 이벤트는 어느 시점에 호출이 되나요?

### ISSUE THREAD

**Issue by biztalk-ts** [navertalk/chatbot-api#125]
persistentMenu를 추가해서 바로가기 메뉴를 넣고 싶은데 

open event를 받는 시점에 response에 persistentMenu를 담아서 보내줬는데

실제 화면상에는 바로가기 메뉴가 생성이 안되더라구요..

persistentMenu를 이용하려면 webhook에서 어떻게 처리해야하나요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

`Response`에 `persistentMenu`를 처리하는 로직에 버그가 있었습니다.
확인 후 패치하여 운영 서비스에 반영하였습니다. 이용에 불편을 드려 죄송합니다.

참고로 `open`이벤트의 응답에 `persistentMenu`설정을 담아서 응답하더라도

- 사용자가 채팅을 보고 있는 상황에선 실시간성으로 변경되는 것이 아니고,
- `persistentMenu`가 사용자 별로 셋업되는 것이 아니라 파트너 별로 셋업되는 것이기 때문에 다른 사용자에게도 영향을 미칠 수 있다는 점

을 유의하셔야 합니다. 따라서 챗봇 시나리오에 `persistentMenu`를 셋업하는 로직을 넣기 보다는 별도로 API 호출을 통하여 셋업하시는 것을 추천드립니다.

감사합니다.
