### ISSUE TITLE
send 이벤트 관련 문의 드립니다

### ISSUE THREAD

**Issue by biztalk-ts** [navertalk/chatbot-api#126]
webhook에서 사용자가 보낸 send 이벤트가 어느 시점에 발화를 입력해서 보낸건지 
확인 할 수 있는 방법이 있나요?

예를 들면 '주문 할 제품을 입력해주세요.' 라고 webhook에서 보낸 메세지를 보고

사용자가 '머그컵' 이라고 입력했을때와

톡톡에 들어오자마자 사용자가 '머그컵' 이라고 입력했을때 webhook 로그 상에는

동일한 body로 request가 들어와서요

어떤식으로 판단을 해야 할까요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

웹훅 이벤트 중에서 `echo` 이벤트가 있는데요. ([참고](https://github.com/navertalk/chatbot-api#echo-%EC%9D%B4%EB%B2%A4%ED%8A%B8))
해당 이벤트는 챗봇이 송신한 이벤트를 다시 돌려받을 수 있는 이벤트 입니다. 따라서

- `open` 이벤트 이후에 챗봇이 아무 응답도 하지 않았는데, 사용자가 `머그컵`이라고 한 상황
- 챗봇이 `send` 이벤트를 한 뒤 `echo`로 메세지 송신을 확인하였는데, 이 상태에서 사용자가 `머그컵`이라고 한 상황

을 구분할 수 있을 것입니다. `echo` 이벤트를 활용하지 않아도 챗봇이 어떤 응답을 하였는지 여부를 귀사에서 원하는 방식대로 상태값 관리를 통하여 구분하실 수 있을 것입니다. 챗봇 플랫폼에선 별도의 상태값을 관리하여 전달드리지 않습니다. 

이와 별도로 버튼을 통해 시나리오를 구성한다면, 버튼마다 지정된 `code`값을 챗봇에게 전달하기 때문에

- 사용자가 텍스트를 타이핑하여 응답했는지 혹은 버튼을 클릭하여 응답했는지 구분이 가능하며
- 어떤 버튼을 클릭하였는지도 구분이 가능

합니다. 참고부탁드립니다.

감사합니다.
