### ISSUE TITLE
완전히 빈 이벤트가 인입됩니다.

### ISSUE THREAD

**Issue by syoh0708** [navertalk/chatbot-api#128]
NaverEvent(event=null, echoedEvent=null, user=null, partner=null, textContent=null, imageContent=null, options=null)

위와 같이 event type(open, send ...)포함하여 명세에 나와있는 property들이 모두 비어있는 event webhook이 지난 30일간 19번 인입되었는데 확인해주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

확인하고 싶으신 파트너 식별값(톡톡 채팅창 주소에서 `https://talk.naver.com/ct/{파트너_식별값}`)을 알려주셔야 찾을 수 있습니다. 가능하면 발생한 날짜도 같이 알려주시면 찾는데 도움이 되겠습니다.

감사합니다.

**Comment by syoh0708** [comment]
@navertalk 
발생 시각 : June 1 2020 14:00:43 KST
파트너 식별값 : wc2rii
에 대해 빈 이벤트가 인입되었으니 확인해주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

해당 계정을 확인해보니 챗봇을 사용하고 있지않고, 네이버에서 제공하고 있는 `쇼핑봇`을 사용하고 있는 것으로 확인하였습니다. 제가 유추하기엔 `개발자도구 → 알림API`에 웹훅URL을 설정하신 것 같습니다.
`알림 API`의 자세한 내용은 [여기](https://blog.naver.com/naver_talk/220787590511)에서 확인하실 수 있습니다. 참고부탁드립니다.

감사합니다.

**Comment by syoh0708** [comment]
추가적인 이슈 파악되면 다시 문의하도록 하겠습니다.
감사합니다 :)
