### ISSUE TITLE
익스플로러에서 톡톡 내 버튼 클릭하여 팝업창 실행 시 스크롤바가 나타나지 않습니다.

### ISSUE THREAD

**Issue by ever0101** [navertalk/chatbot-api#129]
안녕하세요

해피톡이라는 업체에서 제공하는 네이버톡톡 API를 사용하고 있습니다.
상담 시나리오 중에 특정 버튼을 누르면 자사 쇼핑몰로 연결되는 로직이 있습니다.
크롬, 엣지의 경우에는 스크롤바가 나타나지만, 인터넷 익스플로러의 경우 스크롤바가 나타나지 않는 문제가 있습니다.

위와 관련된 문제를 해결할 수 있는 방법이 있을까요?

**Comment by navertalk** [comment]
안녕하세요. 해당 현상을 확인하기 위해, 톡톡 계정 정보와 자사몰 주소를 아래 메일로 전달해주시면 감사하겠습니다.
dl_talk_agency_support@navercorp.com
