### ISSUE TITLE
혹시 해당하는 기능들이 있는지 질문드립니다.

### ISSUE THREAD

**Issue by JeffCBL** [navertalk/chatbot-api#13]
1. 주소검색
2. 캘린더
3. 시간 선택

도미노 피자의 경우에는 주소검색이 적용되어 있는걸로 보이는데, 사용할 수 있나요?

**Comment by navertalk** [comment]
안녕하세요. 네이버 톡톡입니다.

첫 번째 항목 `주소 검색`은 현재 [프로필 API](https://github.com/navertalk/chatbot-api/blob/master/profile_api_v1.md)를 통해서 제공하고 있습니다. 이를 이용하여 @JeffCBL 님도 도미노 피자와 동일한 경험을 챗봇 이용자들에게 제공하실 수 있습니다.

`캘린더`와 `시간 선택`은 현재 제공되고 있지 않습니다. 그러나 두 항목 외에도 다양한 정보 제공이 될 수 있도록 준비하고 있습니다. 완료되는대로 API 문서가 업데이트될 예정이니, 앞으로도 많은 관심 부탁드립니다.

감사합니다.
