### ISSUE TITLE
개선사항 건의

### ISSUE THREAD

**Issue by lesimor** [navertalk/chatbot-api#14]
1. compositeContent의 이미지 사이즈 설정
 imageContent의 경우 별도의 이미지 사이즈 설정 없이 원본의 가로세로 비율에 맞춰서 노출되는 데에 비해 compositeContent의 경우에는 이미지 노출 부분의 가장자리 크기가 고정되어 있어 원본 이미지의 가로세로 비율을 반영하지 못하는 문제점이 있습니다. 카카오 옐로아이디처럼 가로세로 크기를 직접 설정할 수 있는 기능이 있었으면 좋겠습니다.

2. 말이 다 끝나기 전까지 '...' 표시(아직 멘트가 다 끝나지 않았다는 의미로)
 현재 보내기 API를 이용해 0.5~1초 간의 time interval을 설정하여 순차적으로 메시지를 보내고 모든 메시지 전송이 완료가 되면 톡톡서버에게 status 200 응답을 돌려주는 방식으로 개발을 하였습니다. 

제가 제안하는 방법은 
a) 개발 서버로부터 응답이 오기 전까지 챗봇 측의 대화 말풍선에 '...'표시(페이스북처럼)
b) 메시지 나눠서 보내기 기능 자체를 네이버톡톡 측에서 개발, 말이 다 끝나기 전까지 입력 차단

감사합니다.

**Comment by navertalk** [comment]
안녕하세요
네이버 톡톡입니다. 

건의주셨던 2번기능이 금일 배포되었습니다.  
이벤트 명세서의 "action 이벤트" 내용을 참조하시기 바랍니다. 

감사합니다.
