### ISSUE TITLE
챗봇 운영환경에 대해 문의드립니다.

### ISSUE THREAD

**Issue by blackspo** [navertalk/chatbot-api#15]
챗봇 API 작업을 진행할려고 하는데 
챗봇 API운영을 위한 환경에 대해 알려주시면 고맙겠습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다. 

도움이 되시길 바라며, 아래에 3가지 항목으로 정리했습니다.

1. [웹훅](https://github.com/navertalk/chatbot-api#webhook-%EC%9E%91%EC%84%B1-%EB%B0%A9%EB%B2%95)

가이드에서는 자바와 노드JS 환경에 대해 언급하고 있으나, 그 외에 다양한 환경도 가능합니다.
웹훅 설정을 하시면, 챗봇 플랫폼에서 해당 주소(URL)로 이벤트 정보를 담아서 호출합니다.

2. [메시지 보내기](https://github.com/navertalk/chatbot-api#%EB%B3%B4%EB%82%B4%EA%B8%B0-api-%EC%9E%91%EC%84%B1-%EB%B0%A9%EB%B2%95)

저희가 제공하는 REST API를 통해서 사용자에게 여러 모양의 말풍선을 보내실 수 있습니다.

3. 그 외
* 웹훅을 받으려면 정식 인증기관으로부터 발급받은 유효한 인증서로 TLS를 지원해야합니다.


감사합니다.
