### ISSUE TITLE
잘못된 user 값 에러

### ISSUE THREAD

**Issue by 4020507** [navertalk/chatbot-api#152]
안녕하세요
{"success":false,"resultCode":"02","resultMessage":"잘못된 user 값"}

계속 이러한 에러가 발생하여 질문을 드리게 되었습니다.

data = {
    "event": "send",
    "user": 사용자 식별 값 입력,
    "textContent": {"text": "hello"}
}

message = json.dumps(data) 
test = requests.post(
    'https://gw.talk.naver.com/chatbot/v1/event',
    headers=headers,
    data=message)

print(test.text)

제가 작성한 코드 일부인데 사용자 식별값에서 문제가 발생하는 것 같습니다.
제 자신한테 메시지를 보내려고 하는데 본인 계정의 식별값은 어디서 확인할 수 있나요?

**Comment by navertalk** [comment]
안녕하세요.
네이버 톡톡입니다. 답변이 늦어서 죄송합니다.

유저가 파트너와의 대화창을 열거나(`open`) 말을 걸면 이벤트가 전달되며 해당 이벤트에 `user` 식별값이 포함됩니다. 만약 챗봇 이벤트 옵션에서 `open`이벤트 수신 옵션에 체크하셨다면 유저가 대화창에 진입한 이벤트가 전달되며, `send`이벤트 수신 옵션에 체크하셨다면 유저의 입력값이 전달됩니다. 이 때 전달된 `user`값을 활용하여 `보내기 API`를 호출하시면 이벤트가 유저에게 전달됩니다.

감사합니다.

**Comment by 4020507** [comment]
답변 감사드립니다.

파이썬을 사용하여 제 스스로에게 답장을 보내고, 톡톡에 잘 기록이 되어있는지 확인해 보려고 합니다.

readme에 작성해주신 send 이벤트 구조를 보면 
"user": "al-2eGuGr5WQOnco1_V-FQ"
이런식으로 해서 user에 식별값을 알아야 그 유저한테 메시지를 보낼 수 있는 것 처럼 보이는데, 아닌가요?
 제가 식별값을 잘못적어서 그런가 싶어서요.
말씀해주신 open을 보아도 유저 식별값이 필요해보여서 여쭈어보게 되었습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버 톡톡입니다.

> readme에 작성해주신 send 이벤트 구조를 보면
"user": "al-2eGuGr5WQOnco1_V-FQ"
이런식으로 해서 user에 식별값을 알아야 그 유저한테 메시지를 보낼 수 있는 것 처럼 보이는데, 아닌가요?
제가 식별값을 잘못적어서 그런가 싶어서요.

맞습니다. `send` 이벤트로 유저에게 메세지를 보낼 때 `user`를 반드시 알아야 합니다. 하지만 `open` 이벤트는 파트너(챗봇)가 유저에게 보내는 이벤트가 아니라 유저가 채팅창 진입시 챗봇에게 전달되는 이벤트입니다. 따라서 `open` 이벤트가 발생하면 `user` 식별값을 저장하시거나 바로 응답 이벤트를 보내면 됩니다. 각 이벤트의 설명을 다시 한 번 확인하시면 좋을 것 같습니다.

파이썬을 사용하신다고 했는데, 마침 파이썬으로 작성된 훌륭한 오픈소스 모듈이 있습니다.

https://github.com/hwonyo/naver_talk_sdk

활용하시면 직접 개발하시는 것보다 더 편할 것 같습니다. 소개글은 @hwonyo 님께서 [저희 이슈게시판](https://github.com/navertalk/chatbot-api/issues/75)에 작성하셨었습니다. 참고 부탁드립니다.

감사합니다.

**Comment by 4020507** [comment]
좋은 모듈을 소개해주셔서 감사합니다.
도움이 많이 되었습니다.
