### ISSUE TITLE
네이버 톡톡 leave 이벤트 관련 문의

### ISSUE THREAD

**Issue by velmont** [navertalk/chatbot-api#159]
안녕하세요, chatbot api 사용중 궁금한점이 있어 문의드립니다.

chatbot-api로 웹훅연동을 했을때
특정 유저의 open이벤트가 발생한 경우 해당 유저가 채팅방을 나갔을때 leave가 항상 발생한다고 생각했는데,
유저가 아무 대화도 하지 않고 채팅방을 나간 경우 open이벤트만 발생하고 leave이벤트는 발생하지 않는 것으로 확인됩니다.
예외 케이스가 있는 것 같아서 정확히 leave이벤트가 어떤 경우에 발생하는지, 예외 조건은 무엇인지 확인해주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버 톡톡입니다.

대화방이 최초로 생성되었고 파트너, 유저간 대화가 전혀 없었다면 대화방을 나가더라도 `leave` 이벤트가 발생하지 않습니다.
그 외에는 예외가 없으며, 대화를 나눈 이후엔 대화방에서 나갈 때마다 `leave` 이벤트가 발생합니다.

감사합니다.
