### ISSUE TITLE
Webhook 문의사항

### ISSUE THREAD

**Issue by sunkyung18** [navertalk/chatbot-api#165]
네이버 톡톡 API 신청시 Webhook란 있는 이벤트 받을 URL의 챗봇 API 도메인 서버는 어떻게 구축하나요?

**Comment by sunkyung18** [comment]
빠른답변 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요 네이버 톡톡입니다.
웹훅 수신할 서버 구축과 관련하여 따로 권장드리는 방법은 없습니다.
호스팅 서비스나 클라우드 서비스를 활용하여 구축하실 수 있을 것 같네요.
즐거운 연휴 되십시오.
