### ISSUE TITLE
휴대폰 번호 입력시 오류

### ISSUE THREAD

**Issue by superherosj-rewhite** [navertalk/chatbot-api#17]
안녕하세요.

profile - cellphone 요청 후
'휴대폰 번호를 채팅창에 입력해 주세요.' 출력.
휴대폰 번호를 입력하면 잘못된 형식이라고 나오고 있습니다.
정상적인 핸드폰 번호이며, 다른 분의 핸드폰 번호를 넣어도 동일하게 오류 메세지 출력합니다.

확인을 해보니, (정확한 내용을 몰라 추측한 상황입니다.)
NPAY 혹은 쇼핑 쪽에서 결제를 하면서 핸드폰번호를 인증하였던 회원의 경우는 정상적인것 같습니다.

어떻게 확인을 해야 할까요?

**Comment by navertalk** [comment]
안녕하세요. 
네이버톡톡입니다.

말씀하신 오류는 파라미터 누락으로 발생한 버그였고 패치완료했습니다.
API를 확인하시는데 혼란을 드려 죄송하며, 앞으로 더 나은 API를 제공하도록 하겠습니다.

다가오는 추석명절 즐겁게 보내세요. 감사합니다!
