### ISSUE TITLE
[긴급확인요청] 웹훅 api 미호출

### ISSUE THREAD

**Issue by happytalk-help** [navertalk/chatbot-api#173]
안녕하세요 전일 문의 드렸으나 확인되지 않아 한번 더 문의드립니다.

네이버 아이디 avidenf_2
디즈앤도즈 w4jqi6 채널을 해피톡으로 연동하였을때 네이버 웹훅 api가 미호출됩니다.
빠른 확인부탁드립니다.

**Comment by navertalk** [comment]
https://github.com/navertalk/chatbot-api/issues/172 에 답변 드렸습니다. 중복으로 이슈 닫습니다. 감사합니다.
