### ISSUE TITLE
스토어팜 구매한 고객에게 네이버톡톡 메세지 전송방법 문의

### ISSUE THREAD

**Issue by Dogetothemarssss** [navertalk/chatbot-api#176]
안녕하세요. 문의드립니다.

네이버 스토어팜에서 구매한 고객에게 네이버 톡톡API를 이용하여 메세지를 보내고싶습니다.
API 요청 변수들을 살펴보니, '사용자식별값' 이라는 게 존재하는데요
이 값은 어디서 가져올 수 있는지 궁금합니다.

스토어팜에서 구매한 고객의 NAVER ID 와 이름, 휴대폰번호까지는 자동으로 확인이 되는데,
식별값은 못찾겠네여 ㅜ

안내 부탁드립니다.
감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버 톡톡입니다.

챗봇 API에서 이벤트에 포함되어 전달되는 `user`라는 항목의 값을 '사용자 식별값'이라고 합니다.
이 값은 특정 유저 A가 B나 C 파트너와 대화를 하더라도 겹치지 않는 유일성을 보장하는 값인데요.
문제는 이 값과 네이버의 정보를 매핑할 만한 공통 정보는 존재하지 않는 것으로 보입니다.

왜냐하면 스토어팜에서 구매한 고객의 네이버 아이디와 실명은 챗봇 API에서 제공하지 않으며,
휴대전화번호는 프로필 API를 통해서 얻으실 수도 있으나 네이버 회원정보의 휴대전화번호와 주문 고객이 입력하는 휴대전화번호가
반드시 일치하는 걸 보장할 순 없기 때문입니다.

업무에 참고 부탁드립니다.
감사합니다.

**Comment by tilkowonjun** [comment]
안녕하세요. 답변 감사드립니다.
추가문의드리겠습니다.

https://smartstore.naver.com/bunticket/products/2032750270

이 스토어팜은 3개월내에 구매내역이 존재하는 유저일때,
해당 업체에 네이버톡톡으로 문의하면(아무 메세지만 보내면) 자동으로 주문내역을 끌어와서, 주문내역을 보여주고있습니다.

이런 기능을 구현하려면 어떻게 처리해야하는지 안내 부탁드립니다.ㅜ

감사합니다

**Comment by Dogetothemarssss** [comment]
제 생각에는 네이버 톡톡에 입장한 유저를 식별해서 주문정보를 끌어오는것으로 예상되는데.....
위에 답변주신걸로 봐서는 이런 기능이 없는거같은데.. 어떻게 이 업체는 주문내역을 가져올까요...?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

링크로 알려주신 톡톡 계정에는 챗봇이 연동되어 있지 않은 것으로 보입니다.
해당 업체에서 만든 기능은 제가 구현한 것이 아니라서,, 어떻게 만들었는지는 업체에 문의하는 것이 정확하겠습니다.

도움이 되어드리지 못해 죄송합니다.
