### ISSUE TITLE
연락처 및 닉네임 변경 방법 문의

### ISSUE THREAD

**Issue by superherosj-rewhite** [navertalk/chatbot-api#18]
안녕하세요.

profile API를 통해 전달받은 연락처 및 닉네임을 사용자가 원할 시 (사정에 따라 집에 다른 사람의 연락처로 하고 싶을때) 변경하는 프로세스를 고려하고 있는데요.
다시 profile API를 호출하면 그냥 데이터 전달이 되는데, 이 부분은 어떻게 구현을 해야할지요?
예를들어 핸드폰을 변경하고자 할때, 저희가 따로 핸드폰 인증을 받고 처리를 해야하는지 입니다.

확인 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다. 

현재 저희가 제공하고 있는 프로필API는 해당 네이버 유저의 닉네임과 소유인증된 휴대전화번호입니다.
따라서 원하시는 `닉네임 변경` 혹은 `연락처 변경`의 경우에는 별도의 프로세스를 타도록 로직을 구현하시면 될 듯 합니다.

배달과 연락처를 예로 들어보겠습니다. 배달주문 상품을 "본인 수령"/"타인 수령"을 고르게 한 뒤, 

* 본인일 경우 저희가 제공하는 프로필 API (휴대폰 번호)를 이용
* 타인일 경우 별도로 연락처를 받는 시나리오 진행
  * 이 경우 휴대전화번호의 신뢰성을 위한 별도의 프로세스를 어떻게 진행할 지는 고민

으로 구성하면 어떨까 합니다.

저희 서비스에 관심갖고 이용해주셔서 감사드립니다.
