### ISSUE TITLE
웹훅 API 미호출

### ISSUE THREAD

**Issue by Jeong-jae** [navertalk/chatbot-api#186]
안녕하세요 
웹훅 API 미호출 관련해서 문의드립니다.
톡톡 id : w49iyn
API문서 절차에 따라 진행했는데 들어오지를 않습니다.
확인 부탁드립니다! 

'개발자 도구 > 알림 API'는 정상적으로 들어오는 것을 확인했는데 혹시 뭐가 문제인지 궁금합니다.
감사합니다 :-)

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다. 내부 시스템 오류로 전달되지 않은 현상 확인했습니다 😭 
작업에 불편을 드린점 대단히 죄송하며 제보해주셔서 감사합니다. 🙇

**Comment by Jeong-jae** [comment]
> 안녕하세요. 네이버톡톡입니다. 내부 시스템 오류로 전달되지 않은 현상 확인했습니다 😭 작업에 불편을 드린점 대단히 죄송하며 제보해주셔서 감사합니다. 🙇

혹시 언제 복구되는지 알 수 있을까요? 아직도 되지 않는거 같아서요. 확인 부탁드립니다!😊

**Comment by navertalk** [comment]
@Jeong-jae 
답변이 늦었습니다.
오류 복구 이후에 재현되는 부분은 다른 이슈가 있었습니다. 등록하신 Webhook 서버의 인증기관이 톡톡 시스템에 등록되지 않았던 인증기관이라 추가해두었습니다. 이슈 제발하면 제보부탁드립니다.
감사합니다.
