### ISSUE TITLE
톡톡 접근 구분 (PC or Mobile)

### ISSUE THREAD

**Issue by superherosj-rewhite** [navertalk/chatbot-api#19]
안녕하세요.

사용자가 톡톡에 PC 혹은 모바일로 접근을 하였는지 구분할 수 있는 방법이 있을까요?
네이버페이 연동 전 저희 서비스 결제를 실행해야 하는 이슈가 있어 확인을 하고 있는 중,
현재 저희 서비스는 모바일(Android, iOS)에서만 결제가 이루어 지도록 되어 있습니다.
이에 위 구분이 필요한 상황인데 해당 구분을 전달해주시면, PC 접속이 모바일 접속을 유도하는 안내 메세지를 사용자에게 전달하려 합니다.

확인 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

말씀하시는 모바일 여부에 대한 속성은
