### ISSUE TITLE
고객이 상품 문의시 send 이벤트가 안날라오는거같습니다

### ISSUE THREAD

**Issue by mankicho** [navertalk/chatbot-api#197]
API 문서에 따르면
```
product: 스마트스토어/쇼핑윈도의 상품 페이지에서 톡톡문의로 채팅을 시작하거나, 톡톡 모바일 페이지 위젯 중 다른상품문의를 실행한 경우입니다.
 options 속성에 product 정보를 포함하고 있습니다. 톡톡문의로 유입시에는 typing 등, 사용자의 추가 액션이 있어야 이 textContent가 함께 
전송됩니다.
```
이렇게 설명이 되어있는데

![image](https://user-images.githubusercontent.com/48756287/172553505-01ca2789-89c4-49a3-bba3-dcb76e871be5.png)
위의사진에서 톡톡문의를 누른 뒤, 유저가 typing 등의 추가액션을해도 product 정보가 안날라오는거같아요. 혹시 확인해주실수있나요?

정확히는 유저가 typing 한것은 send 이벤트에 inputType = typing 으로 날라오는데 inputType = product 인 이벤트는 안날라오는거같습니다

**Comment by mankicho** [comment]
혹시 이거 확인됐을까요??

**Comment by navertalk** [comment]
안녕하세요~!

테스트 진행하신 채팅창 주소나 파트너 아이디(wc나 wd 어쩌고) 그리고 언제 하셨는지 일시에 대한 정보 공유 부탁드립니다.

**Comment by mankicho** [comment]
안녕하세요 언제했는지 기억안나서 오늘 2시39분에 해봤는데 여전히 안날라옵니다

파트너 아이디는 w4ar4m 입니다

**Comment by mankicho** [comment]
혹시 요거는 언제쯤 답변 받을수 있을까요??

**Comment by navertalk** [comment]
안녕하세요.
네이버 톡톡입니다.

기다려 주셔서 감사합니다. 현 시간부로 패치되어 정상동작 하는 것을 확인했습니다.
```json
{
  "event": "send",
  "user": "4Zp_aY4AiOiVJ4H20n_acg",
  "messageId": 71,
  "textContent": {
    "text": "이 상품을 문의합니다.",
    "inputType": "product"
  },
  "options": {
    "product": {
      "storeName": "브라운의스토어",
      "name": "테스트",
      "url": "생략",
      "mobileUrl": "생략",
      "thumbUrl": "생략",
      "currencyPrice": "10원",
      "currencyOriginalPrice": "10원"
    },
    "noReflectBot": false,
    "mobile": false
  }
}
```

톡톡 챗봇 서비스 이용에 다시 한 번 감사드립니다.
