### ISSUE TITLE
[공지] 프로필 API (휴대전화번호) 작업이 예정되어 있습니다.

### ISSUE THREAD

**Issue by navertalk** [navertalk/chatbot-api#199]
안녕하세요.
네이버톡톡입니다.

8월 말 경에 네이버 회원 시스템 개선 작업이 새벽 시간에 진행될 예정입니다. 작업은 약 3시간 소요될 것으로 예상되며, **프로필 API** 중에서 "휴대전화번호"필드에 영향을 미치게 됩니다. 영향 범위는 기존에 정보제공동의를 한 회원의 휴대전화번호는 조회되지만, 정보제공동의를 하지 않은 회원의 정보제공동의 절차는 진행되지 않습니다. 

작업 시간동안 "휴대전화번호"필드를 포함한 **프로필 API** 호출 시, 정보제공동의가 되지 않은 회원이 [확인] 버튼을 누른 경우 톡톡화면에서는 시스템 개선 작업중이라는 문구가 안내될 예정입니다. 아래는 예시 화면입니다.

![ddf1991a-7cfe-4dd6-8889-811a5168e410](https://user-images.githubusercontent.com/30263758/185602091-b3d08003-28e4-4071-8846-7ef0d892f6d4.png)

## 정확한 일정은 결정되는대로 이 이슈에 다시 안내드리겠습니다.

**Comment by navertalk** [comment]
안녕하세요. 네이버 톡톡입니다.

위에 안내드린 시스템 개선 작업 일정이 8월말이 아닌 **9월 15일**(목)로 확정됐습니다.
작업 일정은 아래와 같습니다.

[2022년 9월 15일]
| 시 간    | 작 업                                                         |
| ------- | ------------------------------------------------------------ |
| 2:00 AM | 프론트 페이지에서 프로필 제공동의 진행 불가 표시 및 서버 배포 |
|         | 배포 이후 시스템 개선 작업 진행                              |
| 4:30 AM | 원래대로 동작하도록 배포                                     |
| 5:00 AM | 모니터링 및 작업 종료                                        |


감사합니다.

**Comment by navertalk** [comment]
안녕하세요. 네이버 톡톡입니다.

**9월 15일 (목) 에서 9월 21일 (수) 로 변경됐습니다.**

나머지 시간 계획은 동일합니다. 업무에 참고부탁드립니다.
감사합니다.

**Comment by mankicho** [comment]
기존에 정보제공동의를 한 회원의 휴대전화번호는 조회되지만, 정보제공동의를 하지 않은 회원의 정보제공동의 절차는 진행되지 않습니다.

위의 문구가 조금 헷갈려서요

1. 휴대전화번호 값을 기존 정보제공동의를 한 회원들만 제공하고, 앞으로 더이상 제공하지않는다. 

2. 프로필 API 의 필드에 cellphone 만 넣었을경우 정보제공동의 절차를 진행하지않고, nickname, cellphone 을 같이넣은경우 정보제공동의절차를 제공하며, 휴대전화번호도 조회할수있다. 

1번이나 2번중 어떤건가요?? 아니면 다른 의미인가요??

추가로
#197 요것도 확인해주실수 있을까요??

**Comment by navertalk** [comment]
안녕하세요.

작업시간동안(새벽 2시에서 5시까지 약 3시간 동안) 휴대전화번호 필드가 포함된 프로필 API 요청건에 한해서
- 정보제공동의가 되어 있지 않은 유저라면 위에 첨부한 화면이 표시되고, 휴대전화번호 제공동의는 진행되지 않습니다.
- 정보제공동의가 원래 되어 있던 유저라면 휴대전화번호를 웹훅으로 전달합니다. (기존과 동일)

나머지 필드는 전혀 영향을 미치지 않습니다.
새벽 5시 이후(작업이 정상적으로 진행된 경우)엔 기존과 동일하게 동작합니다.

추가로 문의하신 부분에 대한 답변은, 해당 이슈에서 이어가겠습니다.
감사합니다.

**Comment by navertalk** [comment]
안녕하세요.

안내드린 작업에 의해 프로필 API에 실제 영향을 미친 시간이 오전 3시부터 오전 3시 50분입니다. 이후 서비스 이상없는 것 확인했습니다.
혹시 휴대전화번호가 제대로 수신되지 않거나 시나리오가 이전과 다르게 동작한다면 편하게 이슈 등록부탁드립니다.

이슈는 닫겠습니다. 감사합니다.
