### ISSUE TITLE
API 호출 테스트 과정에 파트너 정보 에러라고 뜹니다.

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#20]
실제 API 설정에서 보내기 API 설정을 통해 Authorization 값을 받았는데 
그 값을 이용해 API 호출 테스트를 했습니다.
하지만 응답이 실패로 뜨네요. 파트너 정보 에러라고 하는데 어떤 파트너 값이 잘못된건가요?
어떤 부분이 문제일까요?

curl -X POST \
>     -H "Content-Type: application/json;charset=UTF-8" \
>     -H "Authorization: **********" \
>     -d '{ "event": "send", "user": "al-2eGuGr5WQOnco1_V-FQ", "textContent": { "text": "hello world" } }' \
>     "https://gw.talk.naver.com/chatbot/v1/event"

**결과** 
{"success":false,"resultCode":"02","resultMessage":"partner 정보 에러"}

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

호출하셨을 때의 user값이 예제에 있는 값으로 보입니다.
해당 user값은 사용하실 수 없는 값으로, 웹훅 URL 설정을 통해서 얻는 user값을 사용하시면 되겠습니다.

감사합니다.

**Comment by Weisure** [comment]
user 값을 실제로 웹훅url을 통해서 받은 값을 이용을 했는데도 같은 에러 메시지가 뜹니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

https://github.com/navertalk/chatbot-api/issues/21

위 이슈와 동일한 원인으로 발생한 이슈로 보입니다.
다시 해보시고 문제가 발생하면 말씀해주세요.

감사합니다.
