### ISSUE TITLE
API 호출 에러 관련 문의

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#21]
DEBUG: Curl https://gw.talk.naver.com/chatbot/v1/event JsonData={"event":"send","user":"PGLTJmKZlZUqf9RmSQqKHw","textContent":{"text":"hello world"}}
DEBUG: Curl exec=https://gw.talk.naver.com/chatbot/v1/event
string(75) "{"success":false,"resultCode":"02","resultMessage":"partner 정보 에러"}"

php에서 curl을 이용해서 API 호출 테스트를 하고 있는데
어제 이슈와 동일한 현상이 발생합니다.
어제 답변으로 user 값을 예제 값으로 해서 안된다고 하셨는데 실제 user 키 값으로 해도 파트너 정보 에러라고 나옵니다.

정확하게 "partner 정보 에러" 오류 메시지가 어떨때 나오는지 궁금하네요.

에러 명세서에 보면 resultCode가 02인 경우
request json  문자열 파싱 에러라고 나오는데
혹시 json 구조에 문제가 있거나 필수값이 없는건지 파악이 안되네요.

$authorization = '*************';
$post_data["event"] = "send";
$post_data["user"] = 'PGLTJmKZlZUqf9RmSQqKHw';
$post_data["textContent"] = array("text" => "보내기 API 테스트");
$json = json_encode($post_data);

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

Authorization 구조 변경에 의한 사이드 이펙트가 있어, 해당 버그를 패치하였습니다.
위에서 예로 든 JsonData는 이상없는 데이터이며, 테스트시 통과하는 것을 확인하였습니다.

저희 서비스에 관심갖고 사용해주셔서 감사드립니다.
