### ISSUE TITLE
현재 Profile API의 연락처(cellphone) 응답이 없습니다.

### ISSUE THREAD

**Issue by superherosj-rewhite** [navertalk/chatbot-api#22]
안녕하세요.

현재 테스트를 계속 진행중인데,
Profile API의 연락처 (cellphone) 의 응답이 없습니다.

확인 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

curl -X POST -H 'Content-Type: application/json' -H 'Authorization: {}' -d  '{"event":"profile","user":"EyGAbGzKXM26QeCgY77Qeg","options":{"field":"address"}}'

위처럼 호출시 각각의 프로필 필드에 대해서 정상 동작하는 것을 확인했는데요.
어떻게 하셨는지 알려주시면 파악에 도움이 될 듯 합니다. 감사합니다.

**Comment by superherosj-rewhite** [comment]
curl -X POST -H 'Content-Type: application/json' -H 'Authorization: {}' -d {"event":"profile","user":"g5Hb92ovRbzYlVXbJcT26A","options":{"field":"cellphone"}}

형태로 호출하였으며, 기존에 정상적으로 호출이 되던 사항이었습니다.
지난주 금요일 오후부터 갑자기 안되는 현상이어서 확인 부탁드렸습니다.
현재도 동일하게 진행이 안되고 있습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

로그 확인해보니 프로필 결과를 받고, 응답객체에 다시 프로필 요청하는 것을 확인하였습니다.
해당 비즈니스 로직에서는 프로필을 다시 요청하실 수 있도록 수정하였습니다.

감사합니다.

**Comment by superherosj-rewhite** [comment]
확인 및 적용 고맙습니다.

**Comment by superherosj-rewhite** [comment]
안녕하세요. 
이전 이슈사항에 있던 내용인데요.
현재 해당 부분에서 다시 응답이 오지 않고 있습니다.
확인 부탁드립니다.
