### ISSUE TITLE
톡톡 챗봇 사용시 챗봇 API 초기화 문의

### ISSUE THREAD

**Issue by sjpark-dev** [navertalk/chatbot-api#224]
안녕하세요.
챗봇 API를 먼저 설정하고 톡톡 챗봇을 반영하면 챗봇 API가 초기화되는데
반대로 톡톡 챗봇을 먼저 반영하고 챗봇 API를 설정하면 두가지 기능을 다 사용할 수 있습니다.
이런 경우 버그가 아닌지 문의드립니다.

**Comment by navertalk** [comment]
안녕하세요.

버그가 맞습니다. 저희 정책상 챗봇 API나 톡톡 챗봇(쇼핑챗봇이나 챗봇빌더) 두 종류 중 하나만 사용하게 되어 있습니다.
버그 현상을 활용한 구현은 지양해주시길 부탁드리며, 언제든지 예고없이 조치될 수 있는 점 참고부탁드립니다.

감사합니다.
