### ISSUE TITLE
웹훅 수신 문제

### ISSUE THREAD

**Issue by moonchop** [navertalk/chatbot-api#231]
ID : w4frp1

w4frp1채팅방에 입장했을때, 웹훅을 자체 개발한 서버에 보내도록 설정했습니다.
그러나 10번정도 채팅방에 입장하면 5번은 웹훅이 전송되지 않고, 채팅을 하다가 어느순간 웹훅이 전송되지 않습니다.

확인해주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.

11월 1일자 기준, 해당 파트너에 연동된 챗봇에 웹훅 로그를 확인했는데요. 저희가 이벤트를 전달할 때 일부 이벤트에선 `ReadTimeoutException`이 발생했습니다. 저희는 5초동안 응답을 기다리는데 귀사의 서버에서 5초이상의 처리시간이 소요된 것입니다.

귀사 서버의 병목 지점이 될 만한 로직을 확인하시기 바랍니다. 감사합니다.

**Comment by moonchop** [comment]
안녕하세요. 웹훅 수신에 대해 한가지 더 궁금한 점이 생겨 문의드립니다.
현재 서버는 네이버톡톡 github에 있는 express 예제 코드를 사용했습니다. (서버에서 응답시간이 5초이상 걸리는 상황은 없습니다.)

네이버 채팅창에서 텍스트를 입력하면(고객 입장) 네이버톡톡의 webhook을 통해 서버에 채팅 내용이 전달되도록 했습니다. 
그러나 채팅을 보내던 중, 채팅방에 머물러있는 상태로 아무런 동작을 하지 않고, 30초~1분 뒤에 다시 채팅을 보내면, 서버에 webhook이 전달되지 않습니다. 다시 새로고침을 해야만 채팅이 서버에 전달되는 문제점이 있습니다.

저는 어떠한 상황에서도 채팅을 입력하면 100% loss 없이 서버에 webhook이 전달되면 좋겠습니다. 보내기 API를 통해서는 무조건 채팅방에 text 전달이 가능하다만, 이는 고객 입장이 아닌 상담원 입장이기 때문에 근본적으로 문제를 해결할 수 없었습니다. 

조언해주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.

말씀하신 현상은 저희가 서비스에서 의도하는 바도 아니며 제보된 적도 없는 새로운 이슈네요. 채팅창 주소와 재현하신 시간대를 알려주시면 확인해 보겠습니다. 혹은 메일(주소 : dl_talk_agency_support@navercorp.com)로 자세한 상황을 알려주셔도 좋습니다.

감사합니다.

**Comment by moonchop** [comment]
자세한 사항은 메일로 송신했습니다. 
만약 수신하지 못하셨을 경우 코멘트 남겨주시면 감사하겠습니다.
