### ISSUE TITLE
Webhook 이벤트가 발생하지 않는 이슈

### ISSUE THREAD

**Issue by pjy1368** [navertalk/chatbot-api#242]
안녕하세요, 아래 파트너ID에서 2월 8일부터 현재까지 어떠한 Webhook 이벤트도 날아오지 않고 있습니다.
확인 부탁드립니다.
파트너 ID: w4mz7e

**Comment by navertalk** [comment]
안녕하세요.

해당 이슈 픽스하여 웹훅 이벤트가 정상적으로 전달되도록 수정했습니다.
정상동작하는 것 확인했습니다.

감사합니다.
