### ISSUE TITLE
웹훅 미수신 문의

### ISSUE THREAD

**Issue by Jeong-jae** [navertalk/chatbot-api#247]
안녕하세요!

웹훅 이벤트가 발생하지 않아 문의드립니다.
톡톡 id : w49iyn

'알림 API'는 정상적으로 알림이 오는데 그 외 다른 이벤트는 하나도 들어오지 않네요.
시간되실 때 확인 부탁드리겠습니다.
감사합니다 :-)

**Comment by navertalk** [comment]
안녕하세요.

웹훅URL로 등록한 도메인과 통신 도중 SSLHandshakeException이 발생하였습니다. 저희 측에 최신화되지 않은 인증서 정보로 인해 발생한 것으로 파악되어 오늘 중으로 배포하여 정상적으로 통신되도록 반영될 예정입니다.

감사합니다.

**Comment by Jeong-jae** [comment]
안녕하세요!
아직 반영이 되지 않은 거 같은데 혹시 다음 주에는 가능한 건지 알 수 있을까요?

감사합니다.

**Comment by navertalk** [comment]
안녕하세요.

다시 확인 부탁드립니다.

감사합니다.

**Comment by Jeong-jae** [comment]
정상 확인했습니다. 감사합니다!
