### ISSUE TITLE
엘리먼트에 옵션 버튼 문의

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#25]
엘리먼트 리스트에 텍스트 버튼, 링크 버튼은 잘 달리는데
옵션 버튼을 달려고 하니 응답이 없네요.
아래는 talktalk 서버로 전송하는 json문자열입니다.

{
	"event": "send",
	"compositeContent": {
		"compositeList": [{
			"title": "\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc81c\ubaa9",
			"description": "\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85\r\n\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85\r\n\uac1c\ubc1c \ud14c\uc2a4\ud2b8 \uc124\uba85",
			"image": "http:\/\/chatbot.drsotong.com\/data\/service\/2017\/10\/hospital_image_1508736275.png",
			"elementList": {
				"type": "LIST",
				"data": [{
					"title": "\uc9c4\ub8cc\uc548\ub0b4 \ud14c\uc2a4\ud2b8",
					"description": "\uc9c4\ub8cc \uc548\ub0b4 \ud14c\uc2a4\ud2b8 \uc124\uba851",
					"subDescription": "\uc9c4\ub8cc \uc548\ub0b4 \ud14c\uc2a4\ud2b8 \uc124\uba852",
					"image": {
						"imageUrl": "http:\/\/chatbot.drsotong.com\/data\/service\/2017\/10\/hospital_image_1508736285.png"
					},
					"button": {
						"type": "OPTION",
						"data": {
							"title": "\uc2dc\uc220\uc758 \uc8fc\uc758\uc0ac\ud56d",
							"buttonList": [{
								"type": "TEXT",
								"data": {
									"title": "\uc635\uc158-\ud14d\uc2a4\ud2b8\ubc84\ud2bc",
									"code": "opt1"
								}
							}, {
								"type": "LINK",
								"data": {
									"title": "\uc635\uc158-\ub9c1\ud06c\ubc84\ud2bc",
									"url": "http:\/\/www.naver.com",
									"mobileUrl": "http:\/\/m.naver.com"
								}
							}]
						}
					}
				}]
			},
			"buttonList": null
		}, {
			"title": "\uc2dc\uc220\uba851",
			"description": "\uc2dc\uc220\uac1c\uc694(\ub450\uc904\uc774\ub0b4\ub85c\ubd80\ud0c1\ub4dc\ub9bd\ub2c8\ub2e4)",
			"image": "http:\/\/chatbot.drsotong.com\/data\/service\/2017\/07\/hospital_image_1500629066.png",
			"elementList": null,
			"buttonList": null
		}, {
			"title": "\uc804\ud654\ubc88\ud638 \uc548\ub0b4",
			"description": "\ubcd1\uc6d0 \ub300\ud45c\uc804\ud654 or \ub2f4\ub2f9\uc790 \uc804\ud654\ubc88\ud638 \ubc14\ub85c\uac00\uae30\uc785\ub2c8\ub2e4.(\uc218\uc815\ud574\uc11c)\r\n\uc804\ud654\ubc88\ud638 \uc5ec\ub7ec\uac1c \ub2ec\uc544\ub3c4\ub428",
			"image": "http:\/\/chatbot.drsotong.com\/data\/service\/2017\/10\/hospital_image_1508736246.png",
			"elementList": null,
			"buttonList": null
		}]
	},
	"user": "*********************************"
}

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

먼저 보내주신 전문에서 `image`속성에 바로 이미지 URL을 표기하셨는데, 이 부분이 변경되어야 합니다.
```json
"image": "http://chatbot.drsotong.com/data/service/2017/10/hospital_image_1508736275.png"
```

위와 같이 적으시면 안되고 아래와 같이 적으셔야 합니다.
```json
"image": {
  "imageUrl": "http://chatbot.drsotong.com/data/service/2017/10/hospital_image_1508736275.png"
}
```
\
두 번째로 https://github.com/navertalk/chatbot-api#compositecontent 에서 [모든 구성요소를 포함한 사용 예] 섹션을 살펴보시면, 

> **리스트 요소의 버튼은 TEXT와 LINK 타입만 허용된다**

라고 표기가 되어있습니다. 참고하시기 바랍니다. 

감사합니다.
