### ISSUE TITLE
[긴급] Profile API productOrder 미수신 이슈

### ISSUE THREAD

**Issue by happytalkLC** [navertalk/chatbot-api#252]
현재 네이버 톡톡 Profile API를 통해 nickname, phonenumber, productOrder 정보를 요청하였으나 특정 네이버톡톡 계정에서 productOrder 정보가 웹훅을 통해 전달되지 않고 있습니다.
해당 현상을 재현하려 많은 시도를 하였지만 어떤 것이 문제인지 확인이 되지 않아 문의남깁니다.

아래는 테스트를 진행하였던 챗봇 프로필 API 요청시 사용된 고객 구분 값과 시간입니다.
문제 발생 톡톡 ID : w4n6v4
고객 구분 값 : 61HR_65_GaWxP3tWPzT7rw
테스트 진행 시간 : 2024-07-01 14:45, 15:10

빠른 확인 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.

문의하신 파트너의 주문이력을 처리하다가 오류가 발생하여 전달하지 않은 것을 확인했습니다. 관련된 부분을 수정하여 운영서버에 반영했습니다. 서비스에 불편을 드려 죄송합니다.
