### ISSUE TITLE
user값에 대한 질문 입니다.

### ISSUE THREAD

**Issue by yangk2** [navertalk/chatbot-api#26]
{
    "event": "", /* 이벤트명 */
    "options": {
        /* 추가 속성 */
    },
    "user": "al-2eGuGr5WQOnco1_V-FQ" /* 유저 식별값 */
}
리퀘스트시 기본으로 들어오는 user값의 경우 네이버아이디당 유니크한 값인지 궁금합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다. 

user 식별값은 네이버 아이디마다 생성되는 고유한 값입니다.

감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

어제 답변드린 내용에 추가하여 말씀드립니다.
user 식별값은 해당 파트너에 한하여 네이버아이디와 1:1로 일치되는 유니크값입니다.
시간과 상관없이 유저식별값이 기존과 동일하면 같은 회원입니다.
​
그러나 같은 네이버아이디라도 파트너가 다르면 유저식별값도 다릅니다.
