### ISSUE TITLE
Composite - image 의 imageId 설정시 이미지가 나오지 않습니다. (제목수정)

### ISSUE THREAD

**Issue by superherosj-rewhite** [navertalk/chatbot-api#27]
안녕하세요.

Image Upload API를 이용하여, 이미지 등록 후 전달되는 imageId로 imageContent에 사용을 하려 합니다.
현재 테스트로 하나의 이미지를 등록하여 imageId 로 전달하고 있으나, 이미지가 나오지 않고 있습니다.

imageId = "EN4SsVd65r-AZHkge06U0LgQdVBBkkj6ALFVo22KN5m1ECLu1tOgBfHW4nmycmrU7s0VaQmyT5AcAOdqoFPEMvKQV_QcOjWwtqks1UuogUWdT00Ir717IK-tz5_XnPkP"

이며, 확인 부탁드립니다.

이상입니다. 고맙습니다.

**Comment by superherosj-rewhite** [comment]
확인을 해보니, Event 응답에 imageContent를 포함하면 이미지가 노출이 안되고,
직접 Send로 발송한 imageContent의 이미지는 노출이 되고 있습니다.

**Comment by navertalk** [comment]
안녕하세요. 
네이버톡톡입니다. 

말씀하신대로 imageId 파라미터에 대한 변환 로직이 누락되고 있었습니다.
해당 버그는 패치완료되었습니다.

감사합니다.

**Comment by superherosj-rewhite** [comment]
확인 고맙습니다.
