### ISSUE TITLE
event - open 요청이 최대 10번 중복 요청됩니다.

### ISSUE THREAD

**Issue by superherosj-rewhite** [navertalk/chatbot-api#28]
현재 기준으로 전달 드리면,
open 으로 최대 10번까지 중복으로 요청이 전달되고 있습니다.

로그 확인이 가능할까요?

**Comment by navertalk** [comment]
안녕하세요. 
네이버톡톡입니다. 

사용하고 계시는 파트너 계정 아이디를 알려주시면 로그 파악이 가능합니다. 

감사합니다.

**Comment by superherosj-rewhite** [comment]
partner: 'wc4e5m' 입니다.

**Comment by superherosj-rewhite** [comment]
현재도 계속 동일한 증상이 발생합니다. 다만 횟수가 더 늘어난것 같네요.

**Comment by Weisure** [comment]
저도 테스트 도중에 open 이벤트가 여러번 수신되네요.
파트너 : wc5pxp 입니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

메시지에 포함된 이미지의 로딩에 실패했을 경우, 이미지 로딩을 몇 차례 재시도하는 로직이 있습니다. 그런데 이미지 URL이 비어있는 등의 특수한 상황에서 의도하지 않은 "open" 이벤트가 발생할 수 있음을 확인하고 버그 패치했습니다.

문제가 지속되면 말씀부탁드립니다.
감사합니다.
