### ISSUE TITLE
보내기 API 컴포지트 전송 문의

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#29]
보내기 API를 이용해서 다수의 컴포지트들을 캐로셀 형태로 전송하고 있습니다.
경우에 따라서 순차적으로 하나씩 컴포지트들을 연속적으로 출력하고 싶은데
잘 안되네요.
혹시 컴포지트 연속 출력은 네이버톡에서 지원하지 않는 기능인가요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

말씀하시는 "연속 출력"이 어떤 형태인지 이해가 잘 되지 않는데요.

단일 SEND 이벤트의 컴포지트 리스트에 여러 개의 컴포지트를 넣었는데,
이 때 컴포지트가 캐로셀 형태로의 노출이 아니라 
컴포지트 하나씩 유저에게 보내지는 기능을 말씀하는게 맞나요?

이런 기능을 말씀하시는게 맞다면, SEND 이벤트의 컴포지트 리스트에 컴포지트 하나를 넣어서 여러번 호출하시면 되지 않을까요?

감사합니다.

**Comment by Weisure** [comment]
말씀하신대로 send 이벤트 컴포지트 리스트에 컴포지트를 하나씩 넣어서 여러번 호출 했는데도 되지 않아서요.
단순 텍스트 컨텐트로만 이루어져 있을 떄는 여러번 호출시에도 잘됩니다.
