### ISSUE TITLE
quick reply 사라짐

### ISSUE THREAD

**Issue by gentlepie** [navertalk/chatbot-api#3]
PC에서 톡톡을 할 때
메세지 창을 클릭하면 퀵 리플라이가 사라집니다.
(이미지 참고)

![image](https://user-images.githubusercontent.com/25915751/28810949-54558b12-76c7-11e7-8278-0ca296ef4666.png)

![image](https://user-images.githubusercontent.com/25915751/28810941-495afd00-76c7-11e7-9b5d-b7753e409d85.png)

모바일 환경에서는 사라지지 않았습니다.

**Comment by navertalk** [comment]
@gentlepie 
안녕하세요.
사용성을 검토후 모바일버전과 PC버전을 통일된 사용성으로 제공해 드리도록하겠습니다.
감사합니다.

**Comment by navertalk** [comment]
@gentlepie 
안녕하세요.
PC버전에서 메시지 창을 클릭했을 때 퀵 리플라이가 사라지지 않도록 조치했습니다.
감사합니다.
