### ISSUE TITLE
챗붓 api 사용시 네이버 톡톡 일대일대화 메뉴 노출 문의

### ISSUE THREAD

**Issue by happytalk** [navertalk/chatbot-api#30]
안녕하세요.

챗붓 api 이전부터 네이버 톡톡의 api를 이용하여 
채팅상담시스템과 연동하여 운영하고있는 해피톡이라고 합니다.

최근 이슈가 있는 부분이 있어 문의 드립니다.

예정 네이버 톡톡 api 사용시 해당 해피톡과 연동 작업을 진행하면 
네이버 톡톡 파트너 센터의 해당 프로필에서는 일대일 메뉴를 하드하여 운영되었습니다.

근데 챗붓api로 넘어온 후 해당부분이 하이드가 되지 않아 
저희가 api를 이용해 보낸 메시지와 고객이 보낸 메시지는 저희 시스템에서 보여지나
네이버 톡톡 센터에서 상담원(관리자)가 말은 저희 해피톡과 연동이 되지 않는 문제가 있습니다.

하여 챗봇 api를 적용하면 일대일대화메뉴가 노출되는 부분이 정책적으로 결정된 사항인지와
아니라고 하면 일대일 메뉴를 하이드 할 수 있는 방법이 있는지 문의 드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

챗봇 API를 사용하는 파트너와 사용하지 않는 파트너 모두 `상담하기` 메뉴를 통하여 대화에 실시간 참여할 수 있는데요. 기존에 일대일 메뉴를 숨김처리하는 것은 예외적으로 처리한 것입니다. 지속적인 예외 처리를 해드리는 것은 매우 어려운 상황입니다.

해당 메뉴가 노출되어 발생하는 상담원의 메시지는 `echo` 이벤트를 추가하여 수신하시면 됩니다. `echo` 이벤트에 대한 명세는 [여기](https://github.com/navertalk/chatbot-api#echo-%EC%9D%B4%EB%B2%A4%ED%8A%B8) 에서 확인하실 수 있습니다. 

감사합니다.
