### ISSUE TITLE
open 이벤트 발생시 메시지가 두번씩 출력됩니다.

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#33]
현재 생기한의원에 챗봇을 서비스중에 있습니다.
PC를 통해서 생기한의원 챗봇 url에 접근하면 크게 문제가 없는데
모바일 네이버 검색창에서 '생기한의원' 검색 후 브랜드검색에 달려있는 실시간 톡톡 배너를 클릭해 접근했을 경우
같은 메시지가 2번씩 출력되고 있습니다.
빠른 해결 부탁드립니다.
실제 서비스 중인데 저희쪽 문젠지 네이버 쪽 문젠지 파악이 되고있지 않네요.
그 밖에도 최근들어 오후시간대에 응답이 엄청 느리거나 메시지 출력이 안되는 현상도 발생되고 있는데 원인파악 부탁드립니다.

파트너 : wc5zn2
https://talk.naver.com/ct/wc5zn2

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

브랜드검색에서 진입할 때, 경우에 따라 open 이벤트가 두 번 발생하는 현상 확인해서 수정했습니다. 제보주셔서 감사합니다.
오후 시간대에 느려지는 현상은 확인해보고 조치하도록 하겠습니다.

문제가 지속되면 말씀부탁드립니다.
감사합니다.
