### ISSUE TITLE
action 이벤트 버그 리포트

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#35]
이번에 업데이트된 action 이벤트를 저희 서비스에 적용 시키고 있습니다.
현재  사용자 메시지 입력 --> action event 보내기 --> 챗봇 답변 응답(send 메시지 전송) 과정으로 처리되고 있습니다.

모바일 환경에서는 크게 문제 되지 않는데
PC 환경에서는
작성중 이미지 출력 후 챗봇 답변이 출력될 때 화면의 포커스가 젤 밑으로 내려가지 않는 버그가 발생하는거 같습니다.
확인 부탁드립니다

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

typingOn 이벤트 사용 후에 IE에서 스크롤 위치가 잘 맞지않는 문제가 확인되어 개선했습니다. 
크롬 등 다른 브라우저에서는 발생하지 않은 것 같습니다.

제보 주셔서 감사합니다.
