### ISSUE TITLE
Image Upload API 문의

### ISSUE THREAD

**Issue by lunasoft-dev36** [navertalk/chatbot-api#36]
안녕하세요.
Image Upload API에 대해 문의드리려고 합니다.
API를 통해 업로드된 이미지는 기한이 있는지 그리고 기한이 있다면 얼마 후에 톡톡 서버에서 삭제되는지
알려주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

이미지업로드 API를 통해서 등록된 이미지는 별도의 보관 기간없이, 저희 서비스와 생사를 함께 하게 됩니다.

감사합니다.
