### ISSUE TITLE
action 이벤트 관련 문의

### ISSUE THREAD

**Issue by lunasoft-dev36** [navertalk/chatbot-api#37]
action 이벤트를 테스트하고있습니다.

보내기 API를 통해 action 이벤트를 보낼때는 정상작동하지만
Webhook 응답으로 action이벤트를 보내면 동작하지 않습니다.
확인 부탁드립니다!

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡 입니다.

제보 감사드리며, 해당 버그에 대해 패치 완료했습니다.

저희 서비스에 관심 가져주시고, 사용해주셔서 감사드립니다.
따뜻한 연말 되시길 바랍니다.
