### ISSUE TITLE
handover api 테스트중 문의드립니다.

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#38]
현재 handover 기능을 테스트중인데
파트너가 '상담 완료하기' 버튼을 클릭 했을 때 기술문서에 나와있는 메시지가 챗봇으로 전송이 안되는것 같습니다.
handover 이벤트를 검출 할 수가 없네요. 

{
  "event": "handover",
  "user": "al-2eGuGr5WQOnco1_V-FQ",
  "partner": "wc1234",
  "options": {
    "control": "passThread",
    "metadata": "{\"managerNickname\":\"파트너닉네임\",\"autoEnd\":false}"
  }
}

다른걸 설정해야 되는 부분이 있는가요?

**Comment by navertalk** [comment]
안녕하세요. 
네이버톡톡입니다.

예전에 등록해주셨던 이슈를 바탕으로 추론한 파트너 아이디가 `wc5zn2` 인데요.
해당 파트너에 연동된 챗봇에는 `handover` 이벤트가 등록되지 않았습니다.

https://github.com/navertalk/chatbot-api/blob/master/handover_v1.md

위 문서를 참고하여, 이벤트를 먼저 등록하신 뒤 사용하시면 되겠습니다.
감사합니다.

**Comment by keiraydev** [comment]
파트너 아이디 WC5GUO 이구요.
handover  api ON 해놨구요
Webhook에 이벤트 선택에 handover 이벤트 체크하는 게 있나요?
