### ISSUE TITLE
스토어팜 서비스 연동 문의드립니다.

### ISSUE THREAD

**Issue by lunasoft-dev36** [navertalk/chatbot-api#39]
현재 톡톡 파트너센터에서 스토어팜 서비스를 연동하여 테스트 중입니다.

스토어팜 서비스를 연동했을때 유저가 모바일에서 '다른상품문의'버튼을 통해 상품문의를 할 수 있게 되어있는걸로 보여집니다. 하지만 챗봇으로 날아오는 리퀘스트에는 거기에 대한 정보가 아무것도 포함되지 않은채 "inflow" : "list", "referer" : "https://talk.naver.com/" 속성을 가진 open 이벤트만 발생합니다. 따라서 챗봇은 유저가 '다른상품문의'버튼을 눌렀는지 전혀 알 수 없는 것 같습니다.

여기에 대한 부분을 개발 중이신지, 개발 중이시라면 어떠한 방향으로 진행중인지 답변해주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.  
네이버톡톡입니다.

답변이 늦어서 죄송합니다. `다른 상품문의` 버튼을 통한 상품 정보 제공에 대해선 아직 논의중입니다.
어떤 정보를 제공할 지에 따라서 내부 정책과 챗봇 클라이언트에서의 효용성을 고려하고 있어 시간이 소요되고 있습니다. 결론을 얻는대로 업데이트하도록 하겠습니다.

감사합니다.
