### ISSUE TITLE
특정 이벤트시 알림

### ISSUE THREAD

**Issue by SHHam12** [navertalk/chatbot-api#4]
챗봇을 네이버 톡톡에 붙였을시에 유저가 메시지를 보낼때 마다 톡톡알람이 오게 되어서 
알람을 끄게 되면 알람이 아예 안오게 되는데요. 예를 들면 호스트를 호출하던지 주문같은 특별한
이벤트가 발생하였을때 알람을 꺼둔 상태에서도 알람을 울리게 해서 호스트에게 알려줄수 있는 방법이
있을까요??

**Comment by navertalk** [comment]
@SHHam12 

안녕하세요.
네이버톡톡입니다.

네이버톡톡 `파트너센터`에서 챗봇 `API 설정`을 통해 챗봇 연동한 경우 파트너들에게 모든 알림을 OFF할 예정입니다.
아무래도 챗봇이 응대중이기 때문에 상담원에게 알림을 주는것이 경험상 좋지않고 대부분 챗봇을 연동하면 알림을 OFF하기 때문입니다.


말씀하신 특정 메시지에 대해서만 알림을 허용하는 방식에 대해 검토해 봤습니다.

챗봇이 유저에게 보내는 메시지는 `notification`속성을 이용하여 유저알림을 컨트롤할 수 있지만,
유저가 챗봇에게 보내는 메시지에 대해서는 컨트롤할 수 없으며 만약 가능하다면 `compositeContent`에 특수한 버튼을 만들어 알림을 전송하는 케이스만 활용이 가능할 것 같습니다.
챗봇이 유저에게 메시지를 보낼때 챗봇측으로도 알림을 보내는 방법을 구현할 수 있으나 톡톡 정책상 예외케이스가 발생되는 것이라 지금 당장 적용은 힘들고 향후에 좀더나은 방법으로 고려해보겠습니다.

지금 당장 권장드리는 방법은 챗봇에서 알림을 보내는 방법입니다.
또 하나 응용할 수 있는 예는 별도의 파트너(별도 챗봇)를 만들어 `보내기 API`를 통해 관리자를 대상으로 알림을 전송해도 좋을듯합니다.

감사합니다.

**Comment by SHHam12** [comment]
감사합니다!
