### ISSUE TITLE
handover api 질문

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#40]
지난번 답변주셨을 때 해당 파트너에 연동된 챗봇에는 handover 이벤트가 등록되지 않았다고 답변 주셨는데
제가 테스트하고 있는 파트너 아이디는 WC5GUO, wc5px4 입니다.
Handover API 당연히 ON해줬구요.

다른건 다 잘되는데 파트너 센터 관리자 페이지에서 '상담완료하기' 버튼을 클릭 했을 때 
상담원과의 대화가 종료되었습니다 라는 메시지를 사용자에게 출력하고 싶습니다.
그렇게 하기 위해서는 'handover' 이벤트를 수신받아야 하는데 
수신이 안되고 있습니다.

챗봇이 파트너에게 주도권을 뺏아 올 경우에는 handover 이벤트 수신이 잘됩니다.
하지만 파트너가 챗봇에게 주도권을 넘겨줄 때 handover 이벤트 수신이 안되네요.
답변 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

말씀해주신 파트너 계정으로 확인해보니,
`상담 완료하기` 버튼을 눌렀을 때, **대화의 주도권이 파트너에게 있지 않았던 것**을 확인하였습니다.

즉 대화의 주도권이 이미 챗봇에게 넘어간 상태에서 `상담 완료하기` 버튼을 누르셨기 때문에
주도권을 챗봇에게 넘기는 절차에서 오류가 발생하였습니다. 
대화를 하는 도중, 대화의 주도권을 챗봇에게 넘기게 되면 대화 목록의 갱신과 더불어 챗봇이 대화를 주도하기 때문에
파트너(상담원)의 `상담 완료하기` 버튼으로 정보를 전달하는 것은 불가합니다. 

혹시 제가 유추하는 시나리오대로 진행하셔서 발생한 문제라면
챗봇이 파트너에게 주도권을 넘긴 뒤, 별도로 주도권을 빼앗지 않고 
상담원이 `상담 완료하기` 버튼을 통해서 상담을 종료하도록 시나리오를 짜보시는 것은 어떠신지요?

감사합니다.

**Comment by Weisure** [comment]
@navertalk 답변감사드릡니다.
 '상담 완료하기' 버튼을 클릭 했을 때에는 대화의 주도권이 파트너에게 있었습니다.
제가 테스트 진행했던 과정에 대해서 설명드리자면

// 파트너에게 주도권 넘김
$handover_arr = array(
            "event" => "handover",
            "user" => $user,
            "partner" => $partner['data'],
            "options" => array(
                "control" => "passThread",
                "targetId" => "1"
            )
        );

이 때 부터는 "send" 이벤트에 standby 값이 true로 들어오는 걸 확인했습니다.
standby가 true일 경우에는 챗봇이 응답을 못하게 코드로 처리를 하고 있습니다.
파트너 창에서 메시지 수신되는 것도 확인했구요. 이후에 파트너의 주도권을 가져오는 행동은 하지 않았구요.
여기서 파트너가  '상담 완료하기' 버튼 클릭했을 때 "handover" 이벤트가 수신이 안되고 있습니다.
하지만 대화의 주도권은 챗봇에게 넘겨 지더군요.
다시 한번 확인 부탁드릴께요.
