### ISSUE TITLE
webhook 관련

### ISSUE THREAD

**Issue by zavp001** [navertalk/chatbot-api#41]
톡톡 api 테스트 할려고 보니 webhook 에 tls 정식인증을 사용하여 정식도메인이 있어야 하는거 같은데요.. 신규로 구축하는 프로젝트라.. 인증과 도메인없이 webhook 에 로컬서버 url로 테스트 가능한 방법이 있는지 알려주세요..

**Comment by Weisure** [comment]
혹시 AWS 사용가능하시면 인증서 발급은 무료로 할 수 있습니다.
기본적으로 제공해주는 아주 긴 도메인을 이용하는 방법도 있는 걸로 알고 있습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

저희 서비스는 현재 최소한의 검증 절차로, 웹훅 프로토콜을 HTTPS로 구축했는지 체크하고 있습니다.
테스트로 가볍게 진행하시기 위해서 @Weisure 님께서 말씀하신것처럼 아마존 서비스 외에도 [Heroku](https://www.heroku.com) 가 있고, 무료로 사용해보실 수 있습니다.

감사합니다.

**Comment by kidkkr** [comment]
로컬에서는 [localtunnel/localtunnel](https://github.com/localtunnel/localtunnel) 을 이용해 잠깐 테스트하는 용으로 쓰실 수 있습니다
