### ISSUE TITLE
프로필 api 관련 질문

### ISSUE THREAD

**Issue by smlee0930** [navertalk/chatbot-api#42]
회원 정보 요청 후 고객이 1분안에 취소를 누른경우

    [event] => profile
    [user] =>   특정유저키
    [options] => Array
        (
            [result] => DISAGREE
        )

이렇게 들어오는데,
partner 값은 안 들어오던데, partner 값도 들어오게 가능한가요??

저희는 여러 업체를 한번에 관리하려고 해서 파트너값이 따로 필요합니다.

**Comment by navertalk** [comment]
안녕하세요. 
네이버 톡톡입니다.

유저 식별값은 파트너별로 다르게 관리되는 값입니다.
따라서 여러 업체를 관리하더라도, 특정 유저가 취소했다는 정보를 파트너별로 관리하셔야 합니다.

즉 어느 파트너의 웹훅URL로 들어온 유저인지 매핑관계를 챗봇에서 가지고 있고,
저희가 전달하는 이벤트의 유저 식별값으로 프로필 정보를 받거나 취소 상태를 인지하면 됩니다.

감사합니다.

**Comment by smlee0930** [comment]
파트너별로 관리는 되고있으나 파트너별로 db서버가 다릅니다. 
유저와 파트너를 매핑하기 위해서 커넥트를 여러번 해야해서 속도면에서 효율성이 떨어지는데,

partner값은 한꺼번에 관리를 하고 있어 partner 값이 있으면 효율성이 매우 올라갈 것 같은데
혹시 개발 가능성이 없는지 다시 한번 문의드립니다.

그리고 회원 정보 요청을 여러번 테스트해보면서 오류가 생긴건지 
제 네이버 개인계정으로 맞는 인증번호를 입력해도 이후에 반응이 없습니다.  여러번 테스트해봐도 동일한 현상이 발생합니다.
같은 파트너로 다른 사람이 인증했을 때는 인증완료가 잘 되는데, 제 계정으로만 안됩니다.
해당 내용 파일로 첨부합니다.  
개인계정이나 파트너 정보가 필요하시면 요청주세요~
![1](https://user-images.githubusercontent.com/33854277/34592520-fb49b2ac-f207-11e7-86d8-4bab63c3c674.png)

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

1. 휴대폰 번호 오류
문제가 있는 네이버계정의 `유저 식별값`을 알려주시면 확인해보도록 하겠습니다.

2. `partner` 정보 제공
추후에 제공할 여지가 있는 정보입니다. 앞으로 더욱 막강한 기능들을 단계적으로 제공할 예정인데요.
말씀하신 부분을 참고하여 오픈할 기능들의 우선 순위를 고려하도록 하겠습니다.

감사합니다.

**Comment by smlee0930** [comment]
안녕하세요. 
1. 휴대폰 번호 오류
문제가 있는 네이버계정의 유저 식별값은 9QjD4XZL3G4IK2YLC__Olg 입니다.
