### ISSUE TITLE
동기식 회신에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by ghdrns31** [navertalk/chatbot-api#44]
안녕하세요,
보내기 API를 이용하지 않고(gw.talk.naver.com 으로 request를 발신하지 않고)
webhook 에 대한 response 만으로 보내기API 형식을 모두 이용할 수 있을른지 문의드립니다.

예)
1. open 이벤트에 대해, compositeContent 를 포험한 send 이벤트 리턴
2. 특정 send 이벤트에 대해, profile 이밴트를 리턴하여 프로필 요청

만약 이렇게 할 경우, resultCode 를 못 보는 것은 감안해야 할 것 같은데...
api 문서 외에 운영 상 기출 에러가 있으시다면 알려 주시면 감사하겠습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

말씀하신대로 별도의 보내기 API 호출없이, 웹훅에 대한 응답을 통해서 원하는 이벤트를 보내시면 됩니다.
기출 에러는 이슈게시판의 `open` 이슈와 `close` 이슈 모두 참고해주시면 되겠습니다.
외에도 궁금하신 점이 있다면 이슈 생성 부탁드리겠습니다.

감사합니다.
