### ISSUE TITLE
스토어팜 톡톡 챗봇 검수 문의.

### ISSUE THREAD

**Issue by camel2** [navertalk/chatbot-api#45]
20일 전 스토어팜 내 톡톡에서 챗봇 신청을 하였는데 아직 검수중이라서 문의드립니다.
언제쯤 검수가 완료되는건지 승인되는 기준이 있는건지 대행사를 이용해야만 
챗봇서비스를 사용할 수 있는지 알고 싶어요.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

저희 서비스는 별도의 대행사를 이용하지 않아도 사용 승인하고 있습니다.
신청하신 파트너의 식별값 (https://talk.naver.com/ct/여기있는 값) 을 알려주시면 확인해보도록 하겠습니다.

감사합니다.

**Comment by camel2** [comment]
wc8043 입니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

신청 서식의 홈페이지 주소를 스토어팜 주소로 적으셔서 승인하지 않았습니다.
스토어팜의 경우, 저희가 제공하는 쇼핑봇 서비스를 점차 확대하여 별도의 챗봇을 만들지 않아도 되도록 목표하고 있습니다.

감사합니다.
