### ISSUE TITLE
echo서버(챗봇예제) 만들기 api부분 문의

### ISSUE THREAD

**Issue by alsdns016** [navertalk/chatbot-api#49]
안녕하세요.

현재 local에서 테스트를 완료후
 '파트너센터 > 챗봇 API > API 설정 메뉴에서 Webhook 영역 이벤트 받을 URL'에 등록하였습니다. 

-------------------------------------------------------------------------------------------
[ 챗봇 API 설명부분]

2. localhost에서 접근 테스트를 합니다.
curl -X POST -H "Content-Type: application/json;charset=UTF-8" -d '{ "event": "test" }' "http://localhost:8080/"
localhost에서 테스트 후 정식 인증서를 사용하여 https://your.domain/ 으로 접근이 가능 해야합니다.

3. URL를 등록합니다.
파트너센터 > 챗봇 API > API 설정 메뉴에서 Webhook 영역 이벤트 받을 URL에 위에서 만든 URL를 등록합니다.
-------------------------------------------------------------------------------------------

등록 후 '네이버 톡톡( https://talk.naver.com/ct/유저식별값 )'을 통하여 서버통신을 하는지 테스트를 해보았지만 
네이버 챗봇서버로 부터 저희쪽서버로 요청이 들어오고 있지않습니다. 

정리하자면,
1. 고객이 톡톡문의를함
2. 네이버 챗봇서버가 'Webhook에 이벤트 받을 URL'로 정상적으로 요청이 해야하나 현재 안되고있음
(코X도 라는 곳에서 정식 인증을 받았습니다.)
3. '이벤트 받는 서버'에서 '네이버 챗봇서버'로부터 요청이 온게 없음

확인을 위하여 제가 알려드려야 할 정보가 있다면 답변 부탁드립니다. 

감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다. 

구성하신 서버의 외부 네트워크망에서 해당 웹훅 URL로 요청이 가능한지 확인해보시기 바랍니다.
저희 서버에서는 별도의 ACL 관리를 하고 있지 않고 있습니다.
따라서 등록하신 웹훅 URL이 외부에서 접근 가능하다면 저희의 웹훅 이벤트도 정상적으로 전달됩니다.

혹시 그래도 문제가 발생한다면, `http://talk.naver.com/ct/파트너식별값` 부분에서 wc로 시작하는 파트너 식별값을 남겨주세요.

감사합니다.
