### ISSUE TITLE
챗봇 API를 통해서 네이버 예약 연동 관련 문의

### ISSUE THREAD

**Issue by hlee2527** [navertalk/chatbot-api#51]
안녕하세요 챗봇 API 관련해서 문의 드립니다.

톡톡 챗봇과 네이버 예약을 통해서 [테스트] 네이버리조트 챗봇처럼 구현하려고 하는데요. 
네이버리조트 챗봇을 보면 입실날짜와 퇴실날짜을 통해 잔여객실 조회해서 예약을 받아볼수 있는 기능이
지원되는 거 같습니다.
잔여객실을 조회하려면 네이버예약 쪽에 쿼리를 던져서 실제 비어있는 객실을 조회를 해야 가능 할 거 같습니다. 여기에 추가로 투숙인원으로 최대인원 값을 같이 파라미터로 던져서 네이버 예약의 상품에서 쿼리 조회가 가능한가요? 현재 관련해서 API가 제공이 되는지요?

예약상품이 5개가 있을 때 예를 들어 2개는 최대인원이 2명이고 3개가 최대인원이 4명까지 가능할 경우
입실날짜와 퇴실날짜, 투숙인원 3명으로 조회를 할 경우 재고가 동일하다고 가정했을 때 최대인원이 4명이 들어가는 객실 3개가 그 날짜에 자동으로 추천이 되어 고객이 원하는 타입으로 선택가능하게끔 만들고 싶습니다.

현재는 단순히 composite 타입으로 호텔 소개와 객실타입 소개 글 및 예약하기 버튼 클릭시 실제 네이버예약 객실 주소로 링크 걸어서 거기서 예약 및 결제가 가능하도록 구현할 수가 있는데 위에서 언급한 기능이 가능하다면 그 쪽으로 바꿔서 구현하고 싶습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

보셨던 네이버리조트 챗봇은 **네이버 예약서비스와 실제로 연동된 시나리오는 아니었습니다.**
시연하기 위해 하드코딩하여 구현한 챗봇이었다고 확인하였습니다.
그래서 기대하시는 시나리오 구현은 어려운 상황인데요.

하지만 다양한 기능과 API를 계속 제공할 예정이니, 지속적인 관심 부탁드립니다. 감사합니다.
