### ISSUE TITLE
핸드오버 API 문의드립니다.

### ISSUE THREAD

**Issue by lunasoft-dev36** [navertalk/chatbot-api#52]
현재 Handover API를 사용중입니다.
그런데 간혹가다 파트너센터의 API설정을 건드리지 않았음에도 불구하고 Handover API 가 자동으로 OFF로 바뀌는 현상이 발생하는 것 같습니다. 어떤 이유에서 그런 동작을 하는지 답변해주시면 감사하겠습니다.

**Comment by lunasoft-dev36** [comment]
더불어 현재 Handover API에서 
 
'resultCode' => '03',
 'resultMessage' => '권한 없는 파트너에 대한 요청',

오류가 계정에 상관없이 발생하고 있는 것 같습니다.
확인 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

먼저 문제가 발생한 부분 사과드립니다. 저희 측에선 파트너가 설정해둔 값을 임의로 변경하지 않습니다.
해당 유형의 문제에 대해서 파악하고 조치하도록 하겠습니다.

핸드오버 API에서 위 결과가 발생하는 이유는 `partner` 파라미터에 넣은 파트너와 
이벤트를 보내는 챗봇간에 연결이 되어 있지 않기 때문입니다. 해당 파라미터 값을 확인해보시기 바랍니다.
그래도 문제가 발생한다면 파트너 아이디를 남겨주시면, 확인해보도록 하겠습니다.

감사합니다.

**Comment by lunasoft-dev36** [comment]
본사 테스트용 계정 2개, 고객사 계정 1개에서 모두 같은 에러가 발생중입니다. (wc58wh,wc52su,wc85fv)
그 전까지는 문제없이 동작했었으나 1월 31일 6시 경부터 갑자기 이러한 문제가 발생하고 있습니다.
partner 파라미터와 이벤트 받을 url 모두 정상적인것을 확인하였습니다.
확인 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

`wc85fv` 계정으로 테스트 진행했습니다.
* 파트너에게 주도권 전달
```sh
curl -X POST -H "Content-Type: application/json" -H "Authorization: 코드" -d '{{"event":"handover","user":"ZMwHw4HNEVv8j-JDDpdktg","options": {"control": "passThread","targetId": 1}}' "https://gw.talk.naver.com/chatbot/v1/event"
```
* 파트너로부터 주도권 뺏기
```sh
curl -X POST -H "Content-Type: application/json" -H "Authorization: 코드" -d '{{"event":"handover","user":"ZMwHw4HNEVv8j-JDDpdktg","options": {"control": "takeThread"}}' "https://gw.talk.naver.com/chatbot/v1/event"
```

위와 같이 요청했을 때 대화의 주도권이 파트너에게 제대로 넘어가는 것을 확인했는데요.
혹시 계속 에러가 발생하고 있나요?

**Comment by lunasoft-dev36** [comment]
계속 같은 에러 발생중입니다.
API로 보내는 메세지 첨부드립니다.

'event' => 'handover',
'user' => 'kZ7AGCb9D1UrxzyrlmJSeQ',
'partner' => 'wc85fv',
'options' => 
  array (
      'control' => 'passThread',
      'targetId' => 1,
  ),
)

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

핸드오버 이벤트로 요청하실 때 `partner` 필드를 빼고 보내주시면 되겠습니다.
해당 필드는 `serviceCode`와 함께 챗봇이 여러 파트너에 연결되었을 때 의미있는 필드인데요.
추후 추가될 기능으로 현재 가이드가 잘못 안내되었습니다. 메뉴얼도 업데이트하였습니다.

착오를 드려 죄송합니다.
