### ISSUE TITLE
웹뷰 API 공개 일정 문의드립니다.

### ISSUE THREAD

**Issue by insvalley** [navertalk/chatbot-api#53]
안녕하세요. 인스밸리입니다.

챗봇 개발에 앞서 웹뷰 API가 언제 공개 되는지 문의 드립니다

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

웹뷰 API는 오늘 오픈될 예정입니다.
오픈 후 문서 업데이트를 통해서 스펙을 전달드리도록 하겠습니다.

감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

웹뷰 사용 가이드 문서 업데이트했습니다.
https://github.com/navertalk/chatbot-api/blob/master/webview_v1.md

감사합니다.
