### ISSUE TITLE
챗봇 API 오류 관련

### ISSUE THREAD

**Issue by JoungEunLee** [navertalk/chatbot-api#54]
챗봇 API compositeContent 예제 부분을 그대로 따라해서 성공메세지가 나왔는데 봇이 응답을 안했습니다.
코드를 확인해보고 예제 마지막에 text : pay부분을 삭제하고 다시 실행했더니 되더군요.
혹시 paykey 설정을 따로 안해서 오류가 난 것일까 생각해보았습니다.

이런 부분에서 오류가 났을때 성공메세지 말고 오류메세지가 나도록 하는것이 좋을것 같습니다.

**Comment by kidkkr** [comment]
저도 같은 걸 느꼈는데 항상 `200`을 응답하는 정책이지요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

지적해주신 부분에 대해선 내부에서도 통감하고 있습니다.
검증 로직을 추가하고 올바른 데이터 규격에 대해서 안내드리고자 하나,
우선 순위에 의해서 다른 기능들을 먼저 추가하고 있습니다.

빠른 시일 내에 자세하고 친절한 응답값을 반환하도록 하겠습니다.
감사합니다.
