### ISSUE TITLE
[handover] 권한 없는 파트너에 대한 요청

### ISSUE THREAD

**Issue by HwangWonYo** [navertalk/chatbot-api#55]
handover 이벤트를 테스트해보는데 "권한 없는 파트너에 대한 요청" 에러가 발생합니다.
handover 이벤트가 깃헙페이지에 등록되고 난 바로 직후 테스트할때는 문제가 없었는데 
지금은 "권한이 없다"는 에러가 나오네요.
사용한 파트너 값은 네이버 톡톡에서 받은 event와 함께 받은 partner 값을 사용하였습니다.

Q:
"권한 없는 파트너에 대한 요청" 에러는 어떤 경우에 발생하나요?
handover를 사용하기 위한 파트너값이 따로 있나요?
아니면 혹시 파트너에 대한 권한이라는 것을 따로 부여 받아야 하는건가요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

현재 저희가 전달하는 이벤트에는 `partner` 필드에 값이 전달되고 있는데요. 보내지 않도록 패치되었습니다.
챗봇 클라이언트에서 이벤트를 보낼 땐, `partner` 필드와 `serviceCode`를 함께 보내야 의미가 있는데요.
추후에 챗봇들 여러 파트너와 연동할 수 있도록 준비하고 있고, 그 때 의미있는 필드가 되겠습니다.

따라서 해당 필드(`partner`)를 제거하고 이벤트를 보내면 정상 동작합니다.
착오를 드려 죄송합니다!

**Comment by HwangWonYo** [comment]
그럼 추후에는 partner 필드가 추가될 수 있겠네요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

네 추후에 추가될 수 있습니다.

감사합니다.
