### ISSUE TITLE
프로필API 외 몇몇 문의 드립니다.

### ISSUE THREAD

**Issue by ghdrns31** [navertalk/chatbot-api#56]
안녕하세요
1. 프로필API 이용에 대해
1-1. 전화변경 버튼
    {"event":"profile", "options":{"field":"cellphone"}} 으로 요청할 경우,
    제3자제공 동의하기 전에는 약관 및 동의버튼이,  동의 후에는 유저 메세지로 전화번호를 보여주며 
   확인/변경 버튼이 나온 후, 한번 소유인증되고 나면 메세지 없이 프로필 정보가 챗봇으로 웹훅 수신되고 있었습니다.
   BHC님 서비스와 같이 '전화변경' 버튼을 넣어 바로 휴대폰번호 입력 받으려면 어떤 형식으로 event 요청해야 할른지요?
 1-2. 프로필 정보 응답
    profile 이벤트와 기타 send 등 이벤트가 별개 세션id로 수신되고 있습니다..
    하나의 채팅방(유저)에서 하나의 세션이 유지되도록도 가능할까요?
  - 파트너id : WC6ZWV  /  2018.2.6  16:16경

그 외 API 와 별개로 제3자 제공동의를 동의 철회하는 방법이  있을지요?
(한 계정 당 동의하는 화면을 한번씩 밖에 확인할 수 없어서...^^;)

2. 전화걸기 링크삽입
  compositeContent 의 description 내에 대표번호를 넣고자 합니다. 예) 1599-9999
자동으로 링크 삽입되지는 않는 듯 해서..혹시 이쪽에서 직접 링크를 지정/삽입하는 방법도 있을까요?

이상,
감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

1-1) 현재 BHC를 포함한 여러 주문챗봇은 저희가 제공하는 `프로필 API`외에 별도로 구현된 프로세스를 타고 있습니다. 해당 버튼을 추가하는 것이 나을지는 내부 논의를 통해서 결정 후, 다시 안내드리도록 하겠습니다.
1-2) 하나의 채팅방(동일한 파트너와 유저)에선 유저값을 식별값으로 사용하시면 됩니다. 왜냐하면 동일한 유저라도 다른 파트너와 대화를 하면, 다른 `user`값을 전달드리고 있기 때문입니다.
1-3) 제 3자 제공동의를 철회하는 방법은 없는데요. 파트너가 달라지면 `제공 동의`가 다시 안내됩니다. 테스트용 아이디 추가로 해결하실 수 있을 듯 한데요. `철회 기능`에 대해서도 내부 논의를 통해서 결정 후, 다시 안내드리도록 하겠습니다. 의견 감사드립니다!

2) 직접 링크를 지정/삽입 하는 방법은 없고, text 필드에서만 지원하고 있는데요. 그 부분에 대한 논의도 진행하도록 하겠습니다. 다양한 의견 감사드립니다.
