### ISSUE TITLE
open 이벤트 건의사항!

### ISSUE THREAD

**Issue by HwangWonYo** [navertalk/chatbot-api#58]
**대화기록이 없는 유저**가 채팅창을 처음 열었을 때 open 이벤트 값에 구별이 있으면 좋겠습니다.
**대화기록이 없는 유저**에 대한 응대는 일반적인 open 이벤트들과 다르게 다뤄지는 경우가 많기 때문입니다.

* 대화기록이 없는 유저: 1. 채팅방을 처음 들어온 유저,  2. 채팅방을 나갔다가 들어온 유저

**Comment by kidkkr** [comment]
유저키는 고유하니까 챗봇 측에서 검증하면 안되나요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

@HwangWonYo 님 의견 감사드립니다. 
하지만 효용성이 얼마나 클 지에 대한 의문과 대화 기록이 없다는 것만으로는 유용하지 않을 수 있다고 생각합니다.
왜냐하면 비즈니스 로직에 따라서 유저에게 일정 시간 같은 말풍선을 보여줄 수도 있고,
혹은 최초라는 구분이 의미가 없을 수도 있기 때문입니다.

해당 유저가 최초 접속인지 아닌지에 대해 판단하기 위해서 매번 DB 조회를 하는 번거로움이 있으시겠지만,
말씀하신대로 다른 부분에서 DB 접근을 줄이는게 어떨까 생각합니다.

관심과 애정으로 지켜봐주셔서 감사드리며, 
네이버 챗봇 파이썬 라이브러리(https://github.com/HwangWonYo/naver_talk_sdk)가 더욱 흥하길 응원하겠습니다.
