### ISSUE TITLE
가끔 대화를 받아오지 못하는 오류

### ISSUE THREAD

**Issue by JoungEunLee** [navertalk/chatbot-api#59]
대화를 하던 도중, 가끔가다가 사용자가 입력한 단어를 받아 오지 못합니다.
내용이 아예 서버로 들어오지 않아서,, 네이버톡에서 req를 보내주지 않는것 같습니다.

저 외에 네이버톡을 사용하시는 다른분도 이런 오류를 겪은적이 있더군요.
확인 부탁드립니다 :)

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

불편을 드려서 죄송합니다.
사용하시는 `wc`로 시작하는 파트너 계정을 알려주시겠어요?
