### ISSUE TITLE
상담요청 버튼의  event타입

### ISSUE THREAD

**Issue by kidkkr** [navertalk/chatbot-api#6]
현재는 아무 messageContent도 포함하지 않는 `send`이벤트로 전송이 되고 있습니다
상담 요청 버튼을 눌렀을때 전송되는 메시지의 경우 따로 이벤트를 빼내어 주어도 괜찮을 것 같습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

상담요청서, 안심전화번호로 상담요청전화, 스티커 전송에 대한 개선버전이 배포되었습니다.
메시지 이벤트에 포함하여 배포되었는데요.

상담요청서의 경우 "상담을 요청합니다."라는 텍스트가
상담요청전화의 경우 "안심전화번호,안심전화번호의 유효기간" 형태의 텍스트가
스티커의 경우 "스티커를 전송했습니다."라는 텍스트가 전달되도록 수정되었습니다.

아울러 사용자의 이벤트가 어느 매개체로 이뤄졌는지에 대해서
전달할 수 있도록 `inputType`이라는 속성이 추가되었습니다.
자세한 사항은 [개선된 API 문서](https://github.com/navertalk/chatbot-api#textcontent)를 확인해주시면 되겠습니다.


마지막으로 emoji 인데요. 인코딩이 euc-kr일 땐 제대로 표현이 되지 않고, utf-8일 경우엔 이상없이 송수신되는 것을 확인하였습니다.
인코딩 이슈일 수 있으니 확인 한 번 부탁드리겠습니다. 그래도 계속 문제가 지속된다면 말씀해주세요.

관심갖고 이용해주셔서 감사드립니다. ^^

**Comment by kidkkr** [comment]
텍스트로만 보내주셔도 처리하는 데 큰 도움이 될 것 같습니다
인코딩은 생각하지 못했는데 확인해보겠습니다. 좋은 연휴 되세요 👍
