### ISSUE TITLE
프로필API 문의 드립니다.

### ISSUE THREAD

**Issue by ghdrns31** [navertalk/chatbot-api#63]
관리자님, 안녕하세요.

프로필API 사용 중에, 제3자 정보제공 동의에서 예상과 다른 작동에 대해 문의드립니다.

-파트너ID : WC6ZWV
- user : Q9OOAPHKaq5wh_jsOCMZPw
- 실행시간 : 2018.3.12 18:04 ~ 18:05

- 현상1)
동의절차 중에는 네이버톡톡과 챗봇 간 연결이 잠시 끊어지는 것으로 API 이해했습니다만,
"동의하기"나 "자세히보기"를 누르면, code:NzMwYTU3:1, gather_agree 등이 send 이벤트로 챗봇 수신되고 있습니다.

- 현상2)
위 진행한 후 아래 데이터로 profile 정보를 요청하면
(요청데이터 {event:profile, options:{field:nickname, agreements:[cellphone]}}
응답에 options : {result : SUCCESS} 만 돌아오고 nickname 컬럼이 존재하지 않습니다..

이상, 확인 부탁드립니다.
감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

현상1)
최초 프로필 요청 시, 사용자의 약관동의/제공동의 상태에 따라 별도의 시나리오를 진행하게 되는데요.
세션타임을 `1분`으로 정하였습니다. 
그래서 유저가 1분이 넘도록 버튼을 누르지 않거나 다른 반응이 없다면 프로필 시나리오는 유효하지 않습니다. 
결국 1분이 지난 시점에 버튼을 누른 경우, 버튼의 텍스트와 함께 코드값이 전달된 경우입니다.
해당 코드값은 저희 내부에서 사용하는 값인데 전달되어 혼란을 드린 점 죄송합니다. 전달되지 않도록 패치하겠습니다.

현상2)
닉네임의 경우, 네이버회원 서비스에서 제공하는 닉네님을 그대로 전달하고 있는데요.
네이버회원 정보에 저장된 닉네임이 없는 경우로 판단됩니다. 
필드에 해당하는 값이 없어서 닉네임 필드가 없이 전달된 것입니다.

감사합니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

제보해 주신 현상2 관련하여 수정 사항이 있어 안내 드립니다. 
네이버 회원 정보에 닉네임이 없는 경우, 마스킹된 ID를 nickname 필드에 전달하도록 수정하여 배포했습니다.
 
감사합니다.
