### ISSUE TITLE
구매이력 활용에 관한 문의드립니다.

### ISSUE THREAD

**Issue by leeyunkyung** [navertalk/chatbot-api#68]
질문1. 네이버 톡톡 서비스에 보면 소비자가 구매이력이 있다면 오른쪽에 최근 3개월 구매이력이 뜨게되는데, 상품주문번호를 저희쪽 서버에 가져와서 활용할수 있는 방법이 있는 지 문의드립니다. 

질문2.  채팅창에 진입했을 때 이벤트 로그에서 유저식별값을 가지고 저희쪽 서버에서 매핑을 해서 주문내역을 가져오고싶은데 방법이 있는 지 문의드립니다. 

질문3. 주문자 id가 주기적으로 암호화되서 저희쪽 서버로 보내지는데  복호화를 따로 해야되는지 아니면 어떠한 방법이 있는지 문의드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

1) 상품주문번호는 `네이버페이`에서 사용하는 값이고 @leeyunkyung 님 서비스에선 활용하실 필요가 없을 것으로 보입니다.
2) 저희가 제공하는 `user` 값은 암호화된 값이면서 유니크합니다. 따라서 이 값으로 특정 유저를 식별하기 위해 사용하실 순 있으나, @leeyunkyung 님 서비스의 회원체계와 매핑하실 수는 없을 듯 합니다. 다만 귀사에 `네아로`가 연동된 경우, 특정 유저를 식별할 수 있는 기능을 추후 제공할 예정입니다.
3) 주문자id 라는 필드는 별도로 제공하고 있지 않는데요. 어떤 필드를 말씀하시는 건가요?

**Comment by leeyunkyung** [comment]
안녕하세요.

저희는 네이버 스토어팜 판매자인데요
쿠폰(핀번호)재전송 이슈가 많아, 챗봇에 재전송 기능을 추가하고 싶습니다.

위에서 말한 재전송 기능은 주문자(네이버)아이디나 주문번호를 매핑하면 구현 가능할 것 같은데요
해당 정보를 받을 방법이 있는지 궁금합니다.
참고로 저희는 주문자의 네이버 아이디를 가지고 있습니다.

확인 부탁 드립니다.
감사합니다.

**Comment by navertalk** [comment]
안녕하세요.

1. 귀사에서 네이버 아이디를 가지고 있다고 하더라도, 
저희가 네이버 아이디와 저희 `user` 식별값의 매핑 정보를 드리지 않기 때문에 해당 기능은 어려움이 있을 듯 합니다.
다만 특정 주문번호의 유저에게 스마트스토어에서 정의한 쿠폰을 전달하는 것은 앞으로 추가될 수 있습니다.
위 기능이 제공하고자 하는 흐름에 부합한가요?

2. 위에서 말씀하시는 쿠폰이 스마트스토어의 혜택관리를 통한 쿠폰 맞나요?
