### ISSUE TITLE
개인정보에서 주소요청시 거리 측정

### ISSUE THREAD

**Issue by SHHam12** [navertalk/chatbot-api#7]
만약에 주문을 하는 업체에 대해 챗봇을 만들 경우 업체와 고객의 주소거리 차이가 많이 나게 되면
배달지원이 불가능 한 상황이 발생하는데요. 이럴 경우를 대비해서 유저위치와 업체의
거리를 측정할 수 있는 기능이 챗봇에 있을까요?

**Comment by navertalk** [comment]
@SHHam12 

안녕하세요.
네이버톡톡입니다.

현재 확장API를 통해 유저 `address`를 요청한 경우 유저의 위/경도값을 제공하고 있습니다.
이때 챗봇만이 알고 있는 지점(배달이 시작되는 곳)정보는 톡톡에서 알 수 가 없습니다.

챗봇에서 유저의 위/경도값을 전달받아 지점의 위/경도값과 비교하여 직선거리를 구하면 거리를 측정할 수 있을거라 생각됩니다.
그러나 도로를 따라 차로 이동하는 경우 단순히 직선거리만 활용할 수 없을듯한데요.
네비게이션 API가 제공된다면 거리/시간 등을 활용해 볼 수 있을듯합니다.

감사합니다.

**Comment by SHHam12** [comment]
감사합니다!
