### ISSUE TITLE
프로필 api 문의드립니다.

### ISSUE THREAD

**Issue by smlee0930** [navertalk/chatbot-api#70]
안녕하세요.
핸드폰번호와 닉네임이 필요해서 userkey로 
{event:profile, "options": { "field": "cellphone", "agreements": ["nickname"]}}} 로 프로필 정보를 요청하면 
응답에 nickname은 없고 cellphone이랑 [result] => SUCCESS 값만 넘어옵니다.

톡톡관리자센터에서 보면 해당 고객은 닉네임이 있는 걸로 나오는데,
요청을 제가 잘못보낸건지, 응답이 잘못된건지 확인부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

프로필 API의 `field`는 하나씩 요청할 수 있습니다. `agreements`는 `field`에 `cellphone`이나 `address`를 요청했을 때, `정보제공동의`를 진행하는 경우에 한해서 약관동의를 함께 받기 위한 필드입니다.

예를 들어 @smlee0930 님의 챗봇에서 특정 유저에게 아래와 같은 `profile` 이벤트를 보냈다고 가정하겠습니다.
```json
{
  ...
  "options": {
    "field": "cellphone",
    "agreements": ["address"]
  }
}
```
이 경우 `휴대전화번호`가 필요하지만, 약관동의를 진행할 경우 `주소`필드도 함께 동의를 받아두겠다는 것입니다.
추후 `주소`필드가 필요할 때에는 약관동의 절차없이 사용자가 원하는 주소를 고르면 챗봇에게 전달될 것입니다.

감사합니다.

**Comment by smlee0930** [comment]
한번에 field 하나씩 요청가능한 것이라면

최초에는 
{event:profile, "options": { "field": "cellphone", "agreements": ["nickname"]}}}로 요청하고

고객이 동의한 경우에
그 이후
{event:profile, "options": { "field": "nickname"}} 을 요청할 경우 약관동의 절차없이
응답으로 닉네임이 전달된다

이 내용이 맞는건가요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

말씀하신 내용이 맞습니다.

감사합니다.
