### ISSUE TITLE
텔레그램과 같이

### ISSUE THREAD

**Issue by taisunglee** [navertalk/chatbot-api#73]
텔레그램과 같이 다른 사이트에서 특정 이벤트가 발생하면(게시글 작성),
http post 방식으로 메시지를 챗봇을 통해 관리자에게 전송할수 있는 방법이 있나요?

**Comment by navertalk** [comment]
안녕하세요. 
네이버톡톡입니다.

다른 사이트에서 특정 이벤트가 발생했을 때 웹훅을 발생시킨다면 가능합니다.

1. 타 사이트의 특정 이벤트 발생으로 웹훅 트리거링 (triggering)
2. 챗봇에서 이벤트 수신
3. 수신된 이벤트를 해석하여 네이버 채팅창으로 관리자에게 메시지 전송

흐름으로 예상합니다. 
감사합니다.
