### ISSUE TITLE
챗봇 작동 관련 문의드립니다.

### ISSUE THREAD

**Issue by hidoctors** [navertalk/chatbot-api#74]
파트너 계정: WCA1NN

안녕하세요. 챗봇 작동 관련 문의드립니다.
개발자도구>챗봇 환경설정 및 챗봇설정관리>네이버챗봇연결 메뉴들을 다 사용함으로 체크해뒀는데도 챗봇이 노출되지 않는 문제가 있습니다. 
[챗봇 편집하기] 메뉴에서 [반영하기] 버튼을 누르면 '챗봇을 사용하고 있지 않습니다. 챗봇을 사용하도록 변경한 다음 챗봇을 톡톡에 반영하시겠습니까?' 라는 문구가 노출되고요. 어떻게 해결해야 할까요?

그리고, 개발자도구>챗봇 API설정 메뉴에 접근시 페이지 주소가 삭제되었다는 화면이 계속 뜨는데, 해결 방법이 알고싶습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

말씀해주신 파트너계정으로 확인해보니, 
`커스텀 챗봇 에디터` 에서 챗봇을 설정하시다가 `개발자 도구`의 `챗봇 API 설정` 메뉴로 설정하신 것으로 확인하였습니다. 
관련해서 버그가 있어서 발생한 오류였습니다. 불편을 드려서 죄송합니다.
사용하시는 파트너 계정이 `챗봇 API 설정`이 가능하도록 수정하였습니다.

참고로 `개발자 도구`의 `챗봇 API 설정`은 챗봇 클라이언트 서버를 운영하며 챗봇의 로직을 직접 구현하는 것입니다.
`커스텀 챗봇 에디터`는 톡톡 계정과 연결된 `스마트 스토어` 및 `쇼핑 윈도` 상품과 여러 메시지를 커스터마이징하여 유저와 상호작용 하도록 도움을 주는 도구입니다.

감사합니다.
