### ISSUE TITLE
챗봇 API - imageContent > imageUrl 관련 문의

### ISSUE THREAD

**Issue by mrshin-sp** [navertalk/chatbot-api#76]
안녕하세요. 챗봇 API 관련 문의드립니다.

자사 제품과 연동 개발 중, 
이미지 전송을 위해 imageContent > imageUrl을 아래와 같이 전달하였습니다.
- http://mrshin.spectra.co.kr:7070/proxy?fileInfo=KSxlfl95O01sTEBBZXwsKzZjX01tYU1afmNjIXxgLG4hbm5ZLmV5O0FlKn5uMHxrTW5uQiooZStcZUxBQ0p5TkBKTClEeWFrX1hYQCoseSRBTForTnlbeDNMYylheT15KUozfiYjYUNcM2xrOzMxTkQlXSMrYyZ8fmNsWTUkKkRcZV8hN0M=&useMime=N&ticketId=KWRlM1pNbjlAJi1jO0FBeUB9LWw0KXhKa04xLSp%2BbThcNC1aKSlhLmtfY3wmM1ojKUtAJSYyKG4y%0AbVpKfV0%2FSl04LQ%3D%3D

이미지 URL이 일반적이지 않습니다.
자사 제품의 다운로드 URL 형태로 암호화된 파라미터를 이용하여 검증 후 파일을 내려주는 구조입니다.

문의 드리고자 하는 것은 위 URL로 imageUrl을 전달하면
이미지가 표시되지 않고, 그냥 메시지 말풍선에 해당 URL이 문자 그대로 표시됩니다.
(챗봇API V1 전에는 이미지가 보였었습니다.)

위의 URL로 이미지가 표시될 수 있는 방법이 있는지 확인 부탁 드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

현재 위 주소로 접근이 불가한데요. URL 확인 부탁드립니다.

**Comment by mrshin-sp** [comment]
아래 URL로 확인 부탁 드립니다~

http://211.63.24.107:7070/proxy?fileInfo=KSxlfl95O01sTEBBZXwsKzZjX01tYU1afmNjIXxgLG4hbm5ZLmV5O0FlKn5uMHxrTW5uQiooZStcZUxBQ0p5TkBKTClEeWFrX1hYQCoseSRBTForTnlbeDNMYylheT15KUozfiYjYUNcM2xrOzMxTkQlXSMrYyZ8fmNsWTUkKkRcZV8hN0M=&useMime=N&ticketId=KWRlM1pNbjlAJi1jO0FBeUB9LWw0KXhKa04xLSp%2BbThcNC1aKSlhLmtfY3wmM1ojKUtAJSYyKG4y%0AbVpKfV0%2FSl04LQ%3D%3D

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

저희가 `챗봇 웹훅 URL` 등록 시 `HTTPS`로 제한하고 있듯이 HTTP 기본 포트인 80, HTTPS 기본 포트인 443을 통하여 `이미지 URL`을 전달해주시면 정상 동작할 것으로 기대됩니다.

감사합니다.

**Comment by mrshin-sp** [comment]
네, 답변 감사합니다~
