### ISSUE TITLE
사용자 대화가 webhook 을 통해 전달되지 않습니다

### ISSUE THREAD

**Issue by banbanmumani** [navertalk/chatbot-api#78]
서버는 api 가이드에 나온 spring boot sample 대로 서버 코드를 작성했습니다.
그리고 인증서 등록한 주소를 webhook url에 등록했는데 서버에서 대화내용을 전달 받지 못합니다.
아이디는 WC6DBJ 입니다.

확인부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

원인을 파악해본 결과 `letsencrypt.org` 에서 발급한 `Let's Encrypt Authority X3` 버전의 인증서를
인증하지 못하는 문제였습니다. 

해당 기관의 `pem`파일은 저희 서버에 추가해도 문제가 되지 않는다고 판단하여 별도의 추가 작업을 완료하였습니다.
작업 이후 @banbanmumani 님의 계정에서 제대로 에코하는 것을 확인하였습니다.


감사합니다.

**Comment by banbanmumani** [comment]
감사합니다. 덕분에 잘 해결했습니다.
