### ISSUE TITLE
textContent와 compositeContent

### ISSUE THREAD

**Issue by SHHam12** [navertalk/chatbot-api#8]
도미노 피자 챗봇을 들어가면 처음에 텍스트가 뜨고 compositeList가 뜨게 되는데요.
이와 같이 구현을 하려면 어떻게 해야 되는 건가요?? compositeContent 안에 textContent를 넣으면 되는건가요? compositeContent안에 textContent를 넣었을때 text만 나오게 되서 질문합니다.

그리고 유저 input을 받기전에 챗봇이 두번 말하게 하려면 response를 두번 보내면 되는건가요??
두번보내도록 코드를 짜봤는데 보내지지가 않아서요...

**Comment by navertalk** [comment]
@SHHam12 
안녕하세요.
네이버톡톡입니다.

말씀하신 `도미노피자챗봇`의 경우 `보내기API`를 통해 2번 `send`이벤트를 보낸 경우입니다.

일반적인 경우 `Webhook` 이벤트에 대해 `Response`에 `send`이벤트 1개를 싣어서 보낼수가 있는데요.
이걸로는 2개의 이벤트를 연속으로 보낼 수 가 없습니다.

챗봇 내부적으로 처리시간이 오래걸리거나 제 3의 API를 호출해야해서 응답이 오래걸리는 경우 `Webhook`에 이벤트를 전송하기보다는 `보내기API`를 추천합니다.

다시말씀드리면, `Webhook`이벤트에 대해 빠르게 `200`으로 응답을 하고, 비동기적으로 내부 프로세싱 후 `보내기API`를 통해 이벤트를 전송하면 타임아웃현상으로 응답 못하는 케이스들이 사라집니다.

감사합니다.

**Comment by SHHam12** [comment]
그러면 보내기 api로 textContent를 보낸 뒤에 res.sendStatus(200)을 한뒤에 다시 response를 보내기 api를 이용해서 보내면 된다는 말씀이신건가요?? 이렇게 해봤는데 되지가 않네요... 유저가 들어 왔을 때나 특정한 이벤트 발생시 챗봇이 두번 반응하려고 하는데 잘 안되네요... 예를 들면 안녕하세요 라고 먼저 보내고 바로 무엇을 도와드릴까요가 한개의 택스트 박스가 아닌 두개의 택스트 박스로 표현을 하려고 하거든요.

**Comment by kidkkr** [comment]
처음 한 번은 사용자가 발생한 request에 대한 response로 보내시고, 연이어서 request를 보내기 API주소로 새로 보내시면 될 것 같아요. 타입은 반드시 `send`로 보내시구요. `{ "event": "send", "textContent": { "text": "무엇을 ... } }`

**Comment by navertalk** [comment]
@SHHam12 
안녕하세요.
네이버톡톡입니다.

@SHHam12님 `send` 두 번 보내기 성공하셨나요?

**Comment by SHHam12** [comment]
아직 계속 시도 중 이에요... 보내기 api로 보내는 방식을 정확이 이해가 아직 안되서 다시 읽어보고 있습니다.

**Comment by navertalk** [comment]
안녕하세요. 
네이버톡톡입니다.

@SHHam12 님, `send` 이벤트 두 번 보내기 성공하셨나요?

**Comment by SHHam12** [comment]
네 성공해서 계속 개발중입니다 성공했다고 답하는 걸 잊고 있었네요... 감사합니다!!
