### ISSUE TITLE
링크오픈오류

### ISSUE THREAD

**Issue by kuj0210** [navertalk/chatbot-api#80]
안녕하세요 네이버 톡톡을 사용해서 다운로드 링크를 전송하는 중에 링크오픈이 잘안돼는 현상을
발견하여 질문드립니다

https://kit-iot-system.tk:443/download/SR0002.png
해당링크입니다. 

서버가 열러있을 때 실험한 결과

각 메신저 / 브라우저에서는 해당 링크가 이상없이 오픈되었느나

네이버 톡톡에서 실행하면 
![image](https://user-images.githubusercontent.com/33398268/40872706-aaf17c40-668d-11e8-874f-d62c79465e95.png)
kit-iot-system.tk:443/download/SR0002.png 로 강제로 바뀝니다. 
학교 컴퓨터라 사용가능한 포트들이 한정되어있어서 가능하면 적은 포트를 사용하고 싶은데 도움부탁드립니다

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

작성해주신 링크가 열리지 않습니다. 첫 번째로 외부 망에서도 접속 가능한 주소인지 확인을 부탁드리고,
두 번째로 443포트만 사용하시는 경우라면, 포트 번호를 제외한 주소를 작성하셔서 테스트 부탁드립니다.
`https://kit-iot-system.tk/download/SR0002.png`

감사합니다.
