### ISSUE TITLE
Open의 inflow문의

### ISSUE THREAD

**Issue by pcappli63** [navertalk/chatbot-api#81]
안녕하세요.
챗봇 개발중에 있습니다.

현재 스토어팜에서 톡톡문의 버튼을 누를 경우 상품에 대한 품절을 확인 할 수 있도록 서비스를 만들고 있는데요.

1. 스토어팜 페이지에서 톡톡문의하기 버튼을 눌러 접근했을 때 inflow가 확인되지 않아 문의드립니다.
모바일에서는 잘 되는데 PC는 원래 안되는 건가요?

접근 주소 : http://smartstore.naver.com/doublestoreshop/products/2898326559
받은 json : "{"event":"open","user":"...","options":{"inflow":"none","friend":false,"under14":false,"under19":false,"mobile":false}}"

2. 그리고 상품 접근 했을 때 뜨는 이미지는 안 뜨게 할 수 없나요??
(참고 이미지 : http://codebank.doublehost.net/sc.jpg)

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

1) `inflow` 파라미터
`inflow`는 `referer`를 기준으로 판단하여 전달하는 값입니다. 그래서 `referer`를 얻을 수 없는 경우에는 `none`으로 전달하고 있는데요. `referer`가 톡톡 서버로 전달되지 않는 경우가 IE로 팝업창이 뜰 때 입니다. 

2) `톡톡 문의` 상품 인입 메시지
스마트스토어 상품 상세페이지에서 `톡톡 문의`버튼을 눌러 접근하는 경우, 판매자와 사용자 모두에게 정보가 제공되는 메시지입니다. 판매자나 챗봇에서 해당 메시지를 변경할 수 있는 방법은 없지만, 이미지가 없어서 기대되는 사용성이나 목적을 말씀해주시면 검토해보도록 하겠습니다.

3) 챗봇을 이용한 품절 확인 서비스
스마트스토어 상품에 대한 사용자 문의를 기민하게 대응하려면, 챗봇 플랫폼에서 전달하는 `상품인입 메시지` 이벤트의 정보로 할 수 있는데요. 아래와 같은 흐름을 확인할 수 있습니다.
* 사용자가 상품 상세 페이지에서 `톡톡 문의`버튼 터치 (혹은 클릭)
* 톡톡 페이지 진입
* 톡톡 페이지에 `상품인입 메시지`가 뜨고
* 사용자가 문의를 하면 상품 정보와 유저의 메시지가 동시에 순서대로 챗봇에 전달
```json
// 챗봇에 전달되는 메시지
// 1) 상품인입 메시지 : 상품 정보에 대한 메시지
{
  "event": "send",
  "user": "...",
  "textContent": {
    "text": "이 상품을 문의합니다.",
    "inputType": "product"
  },
  "options": {
    "product": {
      "storeName": "개발자의 중고샵",
      "name": "200개의 단계별 예제로 배우는 안드로이드 4.0",
      "url": "http://smartstore.naver.com/inflow/outlink/product?p=309672359&tr=tsf&site_preference=device",
      "mobileUrl": "http://m.smartstore.naver.com/inflow/outlink/product?p=309672359&tr=tsf&site_preference=device",
      "thumbUrl": "https://shop-phinf.pstatic.net/20150716_65/pqbdo_1437051783074LGw89_JPEG/43672814967807467_-164086553.jpg?type=f344",
      "currencyPrice": "19,900원",
      "currencyOriginalPrice": "19,900원"
    },
    "mobile": true
  }
}
// 2) 상품인입 메시지가 뜬 뒤, 사용자가 작성한 메시지
{
  "event": "send",
  "user": "...",
  "textContent": {
    "text": "궁금해요",
    "inputType": "typing"
  },
  "options": {
    "mobile": true
  }
}
```
위에서 보시는 것처럼 `options.product`에 있는 정보를 이용하여 로직을 구현하는 것을 추천합니다. 유의할 점은 사용자가 톡톡 페이지 인입 후, 메시지를 작성해야 상품정보와 함께 메시지를 전달한다는 것입니다. `상품인입 메시지`가 떴다고 하더라도 사용자의 입력이 없다면, `open` 이벤트만 전달된 상태입니다.

자세한 내용은 API 문서 업데이트 후에 확인하실 수 있습니다. 감사합니다.

**Comment by pcappli63** [comment]
저희는 Open 이벤트 발생시 quickReply에 품절확인을 포함하여 메시지를 전송하고 있습니다.
그런데 저희가 보낸 메시지가 상품 인입 메시지보다 먼저 발송될 경우 quickReply 버튼이 사라집니다.

이때 어떻게 해결 해야 하나요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

`상품인입 메시지` 이후에 유저의 입력시 응답메시지에 퀵리플라이를 포함한 메시지 전송하는 것을 추천드립니다. 그 이유는 
* `퀵 리플라이 버튼`은 채팅 화면의 맨아래에 위치하는 버튼이므로 다른 콘텐츠에 의해서 사라질 수 있고
* `open` 이벤트는 위에서 설명드렸듯이 IE의 팝업으로 `톡톡문의`를 할 경우, 어느 상품을 문의하는 것인지 정확한 값을 받지 못할 수 있는 위험도 있기 때문입니다.

감사합니다.
