### ISSUE TITLE
갑자기 사용자 대화를 통해서 webhook을 받을 수 없네요.

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#85]
현재 신규 챗봇 엔진 개발중인데
기존 서비스들은 문제없이 webhook을 통해서 이벤트들을 수신을 잘 받고 있습니다.
하지만 현재 새롭게 개발하는 계정은 webhook 이벤트를 수신받을 수 가 없네요..

curl 명령을 통해서는 저희가 구축해놓은 서버쪽으로 데이터가 잘들어옵니다.
이벤트 받는 URL도 틀린게 없는데 왜그럴까요?

현재 테스트중인 계정 아이디는 WC5BXV 입니다.

**Comment by Weisure** [comment]
혹시나 해서 저희 개발 서버 ip를 변경하니 send 이벤트는 수신되는데 그되에 open, leave 이벤트등은 수신되고 있지 않습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

저희 서버 로그의 일부를 아래에 첨부하였습니다. 참고부탁드리겠습니다.
```
(REQUEST)(BODY:{"event":"open","user":"4xnqL1dMFBMJJfV3Xk1SWw","options":{"inflow":"none","friend":false,"under14":false,"under19":false,"mobile":false}})
(RESPONSE)(TIME:0183ms)(STATUS:500)(BODY:{
(REQUEST)(BODY:{"event":"leave","user":"4xnqL1dMFBMJJfV3Xk1SWw","options":{"mobile":false}})
(RESPONSE)(TIME:0226ms)(STATUS:500)(BODY:{
```

감사합니다.

**Comment by navertalk** [comment]
위 로그는 `(REQUEST)`가 챗봇 플랫폼에서 보낸 요청이고, `(RESPONSE)`가 @Weisure 님의 웹서버의 응답입니다. `Http Status`코드가 `500`으로 웹훅을 수신한 서버에서 오류가 발생한 케이스 입니다.
