### ISSUE TITLE
네이버 톡톡 보내기API 속도 문의 드립니다.

### ISSUE THREAD

**Issue by banbanmumani** [navertalk/chatbot-api#86]
안녕하세요.

사용자에게 메세지를 보냈을때 5초 이상 시간이 걸리는 경우가 있어서 문의 드립니다.

webhook 으로 받은 사용자 메세지를 챗봇 서버에서 처리 후, 보내기 API 로 메세지를 보내면 메세지가 사용자에게 전달되는데 5초에서 6초정도 걸리는 경우가 있습니다.
(210번 메세지 전송 테스트를 했을때 13번 5초 이상 시간이 소요되었습니다.)

사용자에게 보내는 메세지는 textContent 나 버튼을 포함한 compositeContent 를 전달하고 있으며 보내기 API 는 apache commons httpclient 를 이용해서 보내고 있습니다.

사용자에게 전달되는 속도를 줄일 수 있는 방법이 있을까요??

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

테스트 진행하신 시간대와 계정에 대한 정보를 알려주시면,
저희쪽에서 개선할 수 있는 부분에 대한 파악을 하는데 도움이 될 것 같습니다.

@banbanmumani 님의 서버에서 처리하는데 시간이 오래 걸리는 현상이라면,
비동기 방식으로 호출하도록 개선하는 걸 추천드립니다. 
스프링프레임워크를 사용하고 계시면 `AsyncRestTemplate`을 활용해 보시는 건 어떠신가요?

감사합니다.

**Comment by banbanmumani** [comment]
안녕하세요.

네이버톡톡에 대화 반응속도에 대해 다시 문의 드립니다. 

내부 로직 처리시간은 0.2초 미만인데 네이버톡톡 api로 메세지를 전송 후 8초 이상 걸리는 증상이 발생해서 문의드립니다.

파트너 계정은 wcdr5j 이며

발생한 시간과 내용은 다음과 같습니다.

```
지연 요청 정보 1
요청 시간
2018-09-28 18:12:22

요청 메세지
{"compositeContent":{"compositeList":[{"buttonList":[{"data":{"code":"제휴신용카드가 분실신고 되어 있는데 분실신고 해제는 어떻게 해야 하나요?","title":"1.선택"},"type":"TEXT"}],"title":"말씀하신 내용을 이해 못했습니다. \n유사한 질문이 있으시면 선택해주세요.\n\n\n\n1. 제휴신용카드가 분실신고 되어 있는데 분실신고 해제는 어떻게 해야 하나요?"},{"buttonList":[{"data":{"code":"제휴신용카드를 분실한 경우 어떻게 해야 하나요?","title":"2.선택"},"type":"TEXT"}],"title":"2. 제휴신용카드를 분실한 경우 어떻게 해야 하나요?"}]},"event":"send","user":"_bbQYMOB1Y22Vn3PywDeFA"}
```

```
지연 요청 정보 2
요청 시간
2018-09-28 18:06:25

요청 메세지
{"compositeContent":{"compositeList":[{"buttonList":[{"data":{"code":"요양보험 갱신거절하는 방법은 어떻게 되나요?","title":"1.선택"},"type":"TEXT"}],"title":"말씀하신 내용을 이해 못했습니다. \n유사한 질문이 있으시면 선택해주세요.\n\n\n\n1. 요양보험 갱신거절하는 방법은 어떻게 되나요?"},{"buttonList":[{"data":{"code":"실손의료비보험 갱신거절하는 방법은 어떻게 되나요?","title":"2.선택"},"type":"TEXT"}],"title":"2. 실손의료비보험 갱신거절하는 방법은 어떻게 되나요?"},{"buttonList":[{"data":{"code":"보험증서를 분실하여 신청하고자 합니다. 신청방법이 어떻게 되나요?","title":"3.선택"},"type":"TEXT"}],"title":"3. 보험증서를 분실하여 신청하고자 합니다. 신청방법이 어떻게 되나요?"},{"buttonList":[{"data":{"code":"요양보험 갱신거절신청을 고객센터를 통해 할 수 있나요?","title":"4.선택"},"type":"TEXT"}],"title":"4. 요양보험 갱신거절신청을 고객센터를 통해 할 수 있나요?"}]},"event":"send","user":"_bbQYMOB1Y22Vn3PywDeFA"}
```

```
지연 요청 정보 3
요청시간
2018-09-28 17:59:02

요청 메세지
{"compositeContent":{"compositeList":[{"buttonList":[],"title":"죄송합니다. 적절한 답변을 준비하지 못했습니다.\n지금은 우체국금융 \"예금 수신\", \"보험 납입\" 분야에 대해서만 일부 시범서비스 중입니다.\n\"예금의 수신\"과 \"보험의 납입\" 업무와 관련된 궁금한 점을 물어봐주세요.\n열심히 공부하여 우체국 금융과 관련된 더 많은 정보를 제공해 드릴 수 있도록 노력하겠습니다.\n\n\n"}]},"event":"send","user":"cOjwJqJeTskCsgIozUwyBA"}
```

확인부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다.
먼저 업무에 불편을 드려 죄송하며, 해당 현상 확인 후 다시 안내드리겠습니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

서버 로그를 확인한 결과는 다음과 같습니다.
`보내기 API 요청 시간`은 챗봇 플랫폼 서버에서 API를 수신한 시간이고
`메시지 DB 저장 시간`은 말 그대로 메시지가 저장된 시간으로, 저장되었다면 채팅창에 반드시 표시됩니다.

- 지연 요청 정보 1
  - 보내기 API 요청 시간 : 2018-09-28 18:12:21
  - 메시지 DB 저장 시간 : 2018-09-28 18:12:22
- 지연 요청 정보 2
  - 보내기 API 요청 시간 : 2018-09-28 18:06:25
  - 메시지 DB 저장 시간 : 2018-09-28 18:06:25
- 지연 요청 정보 3
  - 보내기 API 요청 시간 : 2018-09-28 17:59:04
  - 메시지 DB 저장 시간 : 2018-09-28 17:59:04

말씀하신 시간대에 `wcdr5j` 계정의 메시지를 함께 조회하였지만,
나머지 메시지들도 처리하는데 오래 걸린 메시지는 없었습니다.

로직을 어떻게 구현하셨는지 모르겠지만,
메시지 전송이 즉각 이뤄지는지 체크를 해보셔야 할 것 같습니다.
저희 측에서 처리하는데 수초 이상 걸린 메시지는 없습니다.

감사합니다.
