### ISSUE TITLE
주기적으로 네이버톡톡 쪽에서 이벤트 수신이 되지 않습니다.

### ISSUE THREAD

**Issue by Weisure** [navertalk/chatbot-api#87]
일전에 문의드렸던 내용과는 별개로 주기적으로 톡톡 쪽에서 이벤트가 수신되지 않습니다.
저희 개발 서버 IP를 변경하면 다시 이벤트 수신이 잘되구요.
어떤 이유에 의해서 네이버 쪽에서 저희 서버 ip를 차단하는것이 아닌가 의심스러운데
정확한 원인이 궁금합니다. 개발하는 과정에야 ip를 바꿔가면서 테스트 하면 되는데 실제로 서비스 과정에 이러면 문제가 될것 같습니다. 뭔가 해결책이 있을까요?

저희쪽에서 의심되는 항목은 두가지 인데
 1. 톡톡 쪽에서 수신받은 프로토콜 데이터가 문제가 있을 때
 2. 저희 개발 서버 데몬 프로그램이 강제 종료되었을 때

파트너 아이디 : WC5BXV

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다. 아래 계정과 연동된 챗봇은 현재 정상 동작하고 있고, 통신 로그 상 이상 내용이 없습니다.

https://talk.naver.com/ct/wc5bxv

추후에 다시 이벤트 수신이 안되고 있다면, #84 이슈 내용과 연관있는 것인지 다시 한 번 확인부탁드리겠습니다. 해당 이슈에서는 톡톡에서 챗봇으로 이벤트를 잘 전달하고 있으나, 챗봇에서 500(internal server rror 응답)을 반환하고 있습니다. 

감사합니다.
