### ISSUE TITLE
persistentMenu 갱신 방법에 대해 궁금합니다.

### ISSUE THREAD

**Issue by banbanmumani** [navertalk/chatbot-api#88]
안녕하세요. 

persistentMenu의 구조를 변경 후 바로 반영이 안되고 있습니다. 혹시 변경된 메뉴를 바로 갱신하는 방법을 알 수 있을까요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

페이지를 갱신하시면 바로 최신 상태의 `persistentMenu`를 화면에 표현하고 있습니다.
페이지 갱신을 하지 않으셨다면 `새로고침`하여 확인 부탁드리겠습니다.

감사합니다.

**Comment by banbanmumani** [comment]
우선 새로운 데이터 갱신을 위해 
1. 데스크탑 브라우저 새로고침
1. 다른 데스크탑 브라우저를 통한 접속
1. 모바일 브라우저를 통한 접속
1. 모바일 네이버 앱을 통한 접속
1. 방을 나간 후 재입장
을 시도해봤는데 변화가 없었습니다. 

혹시 제가 메뉴이벤트를 처리하는 부분이 문제 있는지 궁금합니다. 
지금은 인터페이스에서 send, open, friend와 같이 persistentMenu 이벤트가 발생하는 경우에 다음과 같은 데이터를 리턴하고 있습니다.

{"menuContent":[{"menus":[{"data":{"code":"챗봇 안내","title":"챗봇 안내"},"type":"TEXT"}]}],"event":"persistentMenu"}

그런데 만든 인터페이스 로그를 보면 새로 접속해도 persistentMenu 요청이 오지 않는 것을 확인했습니다.

제가 잘못 처리하고 있는것인지 궁금합니다.

**Comment by banbanmumani** [comment]
사용자가 대화 요청 할때 같이 플랫폼에 메뉴 정보를 보냈더니 정상적으로 반영되었습니다. 감사합니다.
