### ISSUE TITLE
새로고침 open 이벤트 

### ISSUE THREAD

**Issue by gentlepie** [navertalk/chatbot-api#9]
새로고침을 통해서 채팅방에 접속할 경우 제공된 문서와는 다르게 option의 inflow 값이 button으로 넘어옵니다.

**Comment by navertalk** [comment]
@gentlepie 
안녕하세요.
네이버톡톡입니다.

말씀하신 `새로고침`에 대해 확인한 결과 기술적으로 구분이 어렵다고 결론 짓었습니다.
이유는 `새로고침`시에 `Request` 헤더 `referer`가 삭제되지 않고 여전히 기존 페이지정보를 가지고 있기 때문입니다.
이를 처리하기위해 별도의 파라미터로 구분해 줄 수 있으나 URL변경은 과도한 스펙으로 여겨져 `open` 이벤트에서 `새로고침`을 식별 안 하는것으로 결정하였습니다.

이것으로 인해 불편을 겪게 해드린점 사과드리며 더 나은 API를 제공해드리기위해 최선을 다 하겠습니다.
감사합니다.

**Comment by gentlepie** [comment]
감사합니다 :)
