### ISSUE TITLE
이벤트 수신이 되지않습니다... 

### ISSUE THREAD

**Issue by hanyoung10** [navertalk/chatbot-api#90]
네이버 톡톡으로 이벤트를 받기 위해 코드를 제공 되어있는 PHP 샘플코드를 이용해 잡아놓고 event.php로 생성을 해놓은 상태입니다. 

[php 샘플]
<?php
  $json_str = file_get_contents('php://input');
  $json_obj = json_decode($json_str);
  print_r($json_obj);
?>

이벤트 받을 URL또한 https://orangetest.net/event.php로 등록을 하고 EVENT 선택을 모두 선택해놓은 상태입니다. 

https://talk.naver.com/wch85p로 접속을 하고 텍스트를 입력하면 open 이벤트와 send 이벤트가 발생하여 위의 URL로 접속을 한다면 JSON형태로 이벤트 수신이 되어야하는걸로 알고있는데 수신이 되지않습니다. 

혹시 제가 잘못알고있는지 피드백 부탁드립니다!!!!

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

이용에 불편을 드려 죄송합니다. 말씀하신 계정을 확인해보니 챗봇 설정 데이터에 문제가 있었습니다.
정상 동작하도록 수정하였고 `open` 이벤트가 제대로 전달되고 응답주는 데이터까지 확인하였습니다.

감사합니다.

**Comment by hanyoung10** [comment]
넵 감사합니다!!

**Comment by hanyoung10** [comment]
안녕하세요 아무래도 제가 원리 파악이 안된것 같습니다. 
1. 제 개인 서버에 putty를 이용하여 event.php를 다음과 같이 작성하였습니다.  
![1](https://user-images.githubusercontent.com/43843588/47536740-dc0d0880-d8fc-11e8-9386-4938cd1604c9.PNG)

2. 이후 접근 테스트까지 완료를 다음과 같이 진행했습니다. 
![2](https://user-images.githubusercontent.com/43843588/47536783-12e31e80-d8fd-11e8-8959-2ba063c544b9.PNG)

3. 마지막으로 https://talk.naver.com/wch85p로 들어가서 이벤트를 발생하고 밑에 보시는 것처럼 URL로 접속해서 이벤트 로그를 확인하려했으나 아무런 이벤트 수신이 안되는 상황입니다. 
![3](https://user-images.githubusercontent.com/43843588/47536816-43c35380-d8fd-11e8-9da8-cd5fd9171742.PNG)

<< 혹시 중간과정에서 놓친 것이 있거나 필수로 해야하는 작업이 있을까요??? >>

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

챗봇플랫폼에서 보낸 이벤트를 화면에서 확인하시려면 로직을 변경하셔야 합니다.

`curl`로 서버에 요청을 보내는 것과 브라우저에서 서버 주소를 치는 것은 HTTP Method만 다를 뿐, **서버에 요청을 보내는 똑같은 동작** 입니다.
PHP의 `print_r` 함수는 PHP 서버의 요청으로 들어온 `json_obj` 데이터를 출력하여 응답하고 있으니, 해당 데이터를 별도로 로그 파일에 쓰거나 트레이스하면 데이터가 어떻게 들어오는지 파악하실 수 있겠습니다.

혹은 이렇게 해보시면 톡톡에서 유저가 파트너에게 보내는 메시지에 `echo: ` 라는 문자열이 붙어서 챗봇이 대답하게 되는데요.

```php
<?php
$json_str = file_get_contents('php://input');
$json_obj = json_decode($json_str);
$req_text = $json_obj->textContent->text;

$response = array();
$response["event"] = "send";
$response["textContent"] = array();
$response["textContent"]["text"] = "echo: ".$req_text;

print_r(json_encode($response));
```

https://github.com/navertalk/chatbot-api#이벤트-명세 에 정의된 대로 `$response` 데이터를 만들어서 응답하시거나, 챗봇플랫폼 서버로 HTTP 요청을 보내시면 되겠습니다.

감사합니다.

**Comment by hanyoung10** [comment]
답변 감사드립니다!!! 
덕분에 해결하였으며 open이벤트와 send이벤트를 받았을 때 자동 응답 되도록 설정하였습니다. 

귀찮게 해드려서 죄송한데 ㅋㅋ 위에서 말씀해주신게 이해가 잘 안가서요..
사용자를 식별하는 키와 같이 REQUEST로 들어오는 이벤트 로그를 특정파일을 만들어 print_r 함수로 
특정파일에 저장하면 된다는 말씀이신가요??

(PHP가 처음이라 양해부탁드립니다 ㅠㅠㅠ)

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

저도 PHP를 사용해본 적이 없어서(😂) 모범 사례를 알려드리지 못해서 답답하네요.
여러 가지 방법이 있겠지만 간단한 애플리케이션이라면 `error_log`라는 함수를 이용하여 로깅할 수 있겠습니다.
아래와 같이 `log_message()`라는 메서드를 별도로 정의하여 호출하는 방법이 한 가지가 있겠고요.

```php
# 참고 : http://php.net/manual/kr/function.error-log.php
function log_message($message) {
    error_log($message, 3, '[나의 로그 파일 경로]/chatbot.log');
}

...

log_message("user: ".$json_obj->user."text : ".$req_text."\n");
print_r(json_encode($response));
```

다른 방법으론 본격 PHP 개발자들은 로깅용 라이브러리나 프레임워크를 쓰실 것 같습니다.
(참고 : https://www.lesstif.com/pages/viewpage.action?pageId=23757072)

더 자세한 내용은 PHP개발 커뮤니티나 학습을 통하여 구현하시는 게 탁월한 선택이실거라 생각합니다.
재밌고 인기있는 챗봇 기대하고 응원하겠습니다.

감사합니다.
