### ISSUE TITLE
네이버 톡톡 챗봇 이벤트 수신이 되지 않습니다.

### ISSUE THREAD

**Issue by reactor-lee** [navertalk/chatbot-api#91]
안녕하세요 

지난주 확인 결과 이벤트 수신이 제대로 이루어지지 않아 문의 드립니다.

https://www.hellobot.co.kr/naver/lamama
현재 셋팅된 서버는 이상이 없는 걸로 확인됩니다.
postman / 타서비스 활용시 문제 없었습니다.

혹시 이벤트 수신에 이슈가 있거나 변경해야 할 히스토리가 있다면

말씀해주시면 감사하겠습니다.

확인 부탁드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

헬로봇 챗봇 서버로 이벤트를 전달하려고 통신하는 중 `SSL Handshake Exception`이 발생하였습니다.
저희 측에서 코모도사의 `PEM`파일을 추가하여 해결하였습니다.

현재 정상 동작하는것 확인하였습니다.
사용에 불편을 드려 죄송합니다. 😥

**Comment by reactor-lee** [comment]
네 정상동작 확인했습니다. 빠른 대응 감사드립니다.
