### ISSUE TITLE
네이버 톡톡으로 카페 좋아여 한 글들을 보내주는 기능을 구현 할 수 있을까요?

### ISSUE THREAD

**Issue by keelim** [navertalk/chatbot-api#92]
네이버 톡톡으로 카페 좋아여 한 글들을 보내주는 기능을 구현 할 수 있을까요?

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

챗봇과 대화를 하는 사용자가 `좋아요`한 게시글을 알아낼 수 있는 인터페이스가 전혀 없으므로 구현이 어렵습니다. 하지만 추후 제공한다면 다양한 응용이 가능할 것 같은데요. 구현하고자 하시는 목적에 대해서 알려주시면 내부에서 검토해보는데 도움이 될 것 같습니다.

현재 네이버 톡톡으로 제공하고 있는 사용자의 데이터는 [프로필 API](https://github.com/navertalk/chatbot-api/blob/master/profile_api_v1.md) 외에는 없습니다. 참고부탁드립니다.

감사합니다.

**Comment by keelim** [comment]
답변 감사합니다. !!!
