### ISSUE TITLE
Profile API 요청 후 webhook 및 api 동작하지 않음

### ISSUE THREAD

**Issue by shimika** [navertalk/chatbot-api#96]
1. 서비스 이용을 위해 고객님의 주소를 선택하여 제공하시려면 '확인' 버튼을 선택해주세요.
이런 프로필 대화가 중간에 끼어든 경우 (api로 전송했습니다)
이후 유저의 대화가 webhook으로 오지 않고, api로 대화를 입력하여도 
```
{
    "success": false,
    "resultCode": "01",
    "resultMessage": "현재 이 사용자에게 메시지를 보낼 수 없음"
}
```

메시지가 뜹니다.
반드시 사용자가 확인을 눌러 동의를 해야만 동의 및 취소 정보를 포함한 웹훅부터 작동이 가능합니다.
이는 의도된 동작인가요?

2. nickname이나 cellphone의 경우에는 최초 동의 이후에는 profile api 요청 시에 바로 return이 오지만, 주소는 동의를 해도 다음에 요청시에 다시 동의 메시지가 뜨는데 의도된 동작인가요?

파트너 id : wc17xa

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

1. 프로필 API의 흐름에 다른 대화를 추가하지 않기 위한 정책입니다. [메뉴얼](https://github.com/navertalk/chatbot-api/blob/master/profile_api_v1.md#profile-api-동작-흐름)의 3번 항목을 참고해주세요.
2. 프로필 항목 중 `주소`의 경우 사용자가 `N페이 배송지 목록` 중에서 골라야 하기 때문입니다. 그래서 동의를 하라는 내용이 아닌 **주소를 선택하라는 내용**으로 확인/취소 버튼을 표시하고 있습니다.

네이버톡톡 챗봇 서비스에 관심을 갖고 이용해주셔서 감사합니다.
