### ISSUE TITLE
네이버 톡톡 연동이 안됩니다.

### ISSUE THREAD

**Issue by raehongkim** [navertalk/chatbot-api#97]
안녕하세요. 

톡톡 배너 스크립트를 홈페이지에 삽입했는데 배너가 꾸준히 보여지는게 아니라

보였다가 안보였다 하는데 해결방법좀 부탁드릴게요.

http://top.hanatour.com/app/wsv/packageproduct/pk-12000.asp?pkg_code=CBP800190401OZN

적용된 위치는 카카오톡 상담하기 오른쪽입니다.

id : WC8DUU

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다.
현재 배너스크립트의 DOM 초기화 로직에 이슈를 발견하여 수정 중에 있습니다.
제보해주셔서 감사드리며, 이슈 조치되면 바로 회신드리겠습니다!

**Comment by raehongkim** [comment]
안녕하세요.

언제쯤 처리가 완료되는지 궁금해요~

**Comment by navertalk** [comment]
안녕하세요. 네이버톡톡입니다. 배너스크립트의 오류가 수정완료되어 알려드립니다.
현재 하나투어 사이트에서 톡톡 배너가 정상적으로 노출되고 있습니다 :)

![image](https://user-images.githubusercontent.com/30263758/52473762-f46a1000-2bd9-11e9-9ba1-41f637b47286.png)

즐거운 주말되세요!

**Comment by raehongkim** [comment]
감사합니다^^
