### ISSUE TITLE
네이버톡톡 API는 무료 제공인가요?

### ISSUE THREAD

**Issue by ITinfo** [navertalk/chatbot-api#99]
안녕하세요~ 네이버톡톡 API 서비스로 챗봇 엔진 개발 예정입니다.
네이버톡톡 API 서비스는 별도의 과금체계가 있는지 아니면 개인/기업과 관계없이 무료로 제공이 되는 것인지 궁금합니다.
답변 부탁 드립니다.

**Comment by navertalk** [comment]
안녕하세요.
네이버톡톡입니다.

개인과 기업 관계없이 모두 무료로 사용하실 수 있습니다.
앞으로 많은 이용 부탁드립니다.

감사합니다.
